### ISSUE TITLE
Small guide for how to install Luminescence in Ubuntu/Linux Mint

### ISSUE THREAD

**Issue by DirkMittelstrass** [R-Lum/Luminescence#109]
I made my self familiar with the Linux distribution Ubuntu in the last weeks and found it quite challenging to get the Luminescence package up and running, especially as I had been a complete Linux newbie. To save others a couple of hours of time in fiddling it out him/herself, here is my short guide for the Luminescence package installation in **Ubuntu 20.04**. This guide should also work for **Linux Mint** because it is based on Ubuntu (Linux Mint is the user-friendly Windows-like version of Linux). Be aware, you will need the system console for the installation process, accessible by pressing _Ctrl-Alt-T._

<br>

**Step 1: Install R and RStudio**

As for December 2021, the R version available in the Ubuntu Software Center is version 3.6. However, you will need version 4.0 or higher to get the Luminescence package running. Follow the guide provided in this link to install the latest version of R: https://cloud.r-project.org/bin/linux/ubuntu/

There exists an alternative way to install R: Download the latest _tar.gz_ file from r-project.org, unpack it and open the file INSTALL. There is an installation guide in it.

Installing RStudio is easy. Download the version for Ubuntu 18 here: https://www.rstudio.com/products/rstudio/download/#download

Right-click at the installation file and execute it via Software Install.

<br>

**Step 2: Install the Luminescence package**

You can install Luminescence with the RStudio installation manager. However, the installation will fail with a "non-zero exit status". As it turns out, you have to install some additional Linux libraries to allow for the installation of all Luminescence package dependencies. At my system I needed to install the following four. Execute the following commands in the system console one after another:

```
sudo apt install libgdal-dev
sudo apt install libssl-dev
sudo apt install libcurl4-openssl-dev
sudo apt install libxml2-dev
```

Retry the Luminescence installation. With some luck, it works now. However, it is quite possible that more libraries are needed at your system (I already installed some other stuff in advance). Search the Luminescence installation log for some missing library file. In three out of four cases, you can simply copy-paste that missing file name into a command line as above. In the fourth case, Google will help. ;-)

**Comment by RLumSK** [comment]
@DirkMittelstrass great and thank you. If OK for you, I would publish this as a tutorial article on r-luminescence.org. \

**Comment by DirkMittelstrass** [comment]
Yes, of course. Feel free to do with the text whatever you want.

**Comment by RLumSK** [comment]
@DirkMittelstrass Done: https://r-luminescence.org/tutorials/luminescence_on_linux/

Thank you!
