### ISSUE TITLE
analyse_SAR.TL() - fix for XSYG usage

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#11]
Function does not work for files imported from XSYG files, due to differently stored irradiation time.

Function should be enhanced.

**Comment by RLumSK** [comment]
I would need an XSYG-file measured with a lexsyg reader containing TL data including the irradiation times ... @Eiskeil

**Comment by Eiskeil** [comment]
I will send it to you directly, uploading did not work here...

**Comment by RLumSK** [comment]
I'll to fix this for 0.7.1

**Comment by RLumSK** [comment]
Does it work now?

**Comment by tzerk** [comment]
Who is this question directed to? I am the author of this issue only because of having moved all our open issues from our old bugtracker to GitHub. I am not sure who originally opened this issue though.

**Comment by RLumSK** [comment]
Sorry: Does it work now @Eiskeil

**Comment by RLumSK** [comment]
@Eiskeil Please check the function, does it work now?

**Comment by RLumSK** [comment]
No one seems to care, which means that it either works or no one needs that functionality.
