### ISSUE TITLE
Example in `write_R2Bin()`not working

### ISSUE THREAD

**Issue by JohannesFriedrich** [R-Lum/Luminescence#110]
**Describe the bug**
The example given in the manual for the function `write_R2BIN()` is not working.

**Please add a minimalistic reproducible example**

```r
library(Luminescence)
data(ExampleData.BINfileData, envir = environment())

temp_file <- temp_file <- tempfile(pattern = "output", fileext = ".bin")
write_R2BIN(CWOSL.SAR.Data, file = temp_file)
```

(BTW: The double `temp_file` is not necessary ;-) )

**Expected behaviour**

**Screenshots**

![Bildschirmfoto 2022-04-04 um 12 57 57](https://user-images.githubusercontent.com/15369350/161530084-a0e31231-91cd-41a0-ab72-3a627a40d5a3.png)

**Session info**

sessionInfo()
R version 4.1.3 (2022-03-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Luminescence_0.9.19

loaded via a namespace (and not attached):
 [1] httr_1.4.2        compiler_4.1.3    magrittr_2.0.3    R6_2.5.1          magick_2.7.3     
 [6] parallel_4.1.3    tools_4.1.3       Rcpp_1.0.8.3      grid_4.1.3        data.table_1.14.2
[11] png_0.1-7

**Comment by RLumSK** [comment]
Thanks @JohannesFriedrich for reporting, I will attend to it.
