### ISSUE TITLE
how to export Component1,2,3 after fit_CWCurve?

### ISSUE THREAD

**Issue by cmdelta** [R-Lum/Luminescence#115]
After decomposing the decay curve with "fit_CWCurve", is it possible to output the specific values of the plot elements in "CW curve fit", such as the specific values of the 3 components, the specific values of the residuals, etc.?

**Comment by RLumSK** [comment]
@cmdelta The values are returned in the output object; see package example:

```r
data(ExampleData.CW_OSL_Curve, envir = environment())

##fit data
fit <- fit_CWCurve(values = ExampleData.CW_OSL_Curve,
                   main = "CW Curve Fit",
                   n.components.max = 4,
                   log = "x")
fit
```r

This gives 
```
 [RLum.Results-class]
	 originator: fit_CWCurve()
	 data: 3
 	 .. $data : data.frame
	 .. $fit : nls
	 .. $component.contribution.matrix : list
	 additional info elements:  1 
```

The elements can be accessed, example: 

```r
fit$data
```

I will close the issue since it is not a bug nor a feature request.

**Comment by cmdelta** [comment]
Sorry, my brain is dead and asked such a funny question. I saw that the source code ended up removing three variables, I should have mixed them up

**Comment by RLumSK** [comment]
@cmdelta No problem, I am happy if it works now.
