### ISSUE TITLE
Plotting functions - Legend outside of plotting area

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#13]
In some cases it would be nice to place the legend of the abanico, kde, etc. plot outside of the plotting area. For some data sets and having activated several statistical parameters to show in the legend it becomes cumbersome to fit the legend within the plotting area (overlapping of legend with data). 

Idea: add 'outside' parameter to 'sum.pos' argument and plot legend on the outer (right|left) margin of the plot. This obviously requires some readjustment of when setting the general layout ('layout','mfrow', 'mfcol'). 

Adjusting the global scale (cex < 1) is not a good option, as it becomes unreadibly small for publication and again requires rescaling in external tools.

**Comment by RLumSK** [comment]
News?

**Comment by RLumSK** [comment]
News?

**Comment by RLumSK** [comment]
Ok, I close this issue. After two years nothing was done. Means it was either not important or not possible to do.
