### ISSUE TITLE
potentially wrong code in plot_GrowthCurve()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#138]
This code  is suspicious:

https://github.com/R-Lum/Luminescence/blob/759a1142651cc557f9fd06c6b061d1aff244cdf9/R/plot_GrowthCurve.R#L588-L594

If `b` is `NA` then `b <- NA` and `b.MC` is not set. I haven't found yet if it can actually cause problems, but by inspection it seems it should have been `b.MC <- NA`.

**Comment by RLumSK** [comment]
The code is fine, because b.MC is not called if `is.na(b) == TRUE`. But I do agree that this is very awkward code.
