### ISSUE TITLE
break up plot_GrowthCurve() into separate functions

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#141]
The function is way too big and more complex than it could be: creating a non-exported function for each of the fit methods would make `plot_GrowthCurve()` easier to follow.

**Comment by mcol** [comment]
The first step would be to create a new function `fit_GrowthCurve()` that only does the fitting, while leaving the plotting side of the code in `plot_GrowthCurve()`. The current callers of `plot_GrowthCurve()` will need to be adjusted, as many of them are just interested in the fitting part.

**Comment by mcol** [comment]
Since the code for plotting is relatively small, I will first rename `plot_GrowthCurve()` to `fit_GrowthCurve()`: this should make it easier to trace the file's git history (also on github, I believe). Then I will create a new `plot_GrowthCurve()` that first calls `fit` than does the plotting.

**Comment by RLumSK** [comment]
@mcol Thank you, yes this seems to be a sensible way and it will allow us to also update the plot output and brush it up a little bit. Please do not forget to add yourself as an author/co-author to the functions you modified significantly.

**Comment by mcol** [comment]
Now we have a new `fit_DoseResponseCurve()` in place! I think it still makes sense to attempt to break it into smaller chunks (in the same file) corresponding to each fitting method, as it's still quite hard to navigate.

**Comment by RLumSK** [comment]
@mcol Yes, please modify as you see fit. The current construction is too verbose.

**Comment by mcol** [comment]
I've consolidate some code, but there's no much advantage in splitting it further as it would require very long argument lists to pass around all the state.
