### ISSUE TITLE
calc_OSLLxTxRatio() - allow the usage of the previous background

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#15]
According to Murray and Wintle (2000) for particular cases it might be necessary to use the background of the Lx curve to correct the Tx curve (use previous background). To account for this the function should be modified as follows: 

Implement new logical parameter `use_previousBG` to use the BG of the Lx curve for the getting the net signal of the Tx curve. 
- Check if the time domain AND the number of channels are similar for both curves, otherwise the option `use_previousBG`has to be reset automatically to `FALSE`
- Check for differences in the signal integral limits in both curves (this is already allowed by the function) to make sure that the background subtraction will not bias the results (...>> parameter k)

**Comment by RLumSK** [comment]
Done.
