### ISSUE TITLE
include the tests/testdata directory in the package

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#168]
The `tests/testdata` directory is currently listed in the `.Rbuildignore` file, presumably to keep the package size small. However, the listing of that directory shows that almost all files are less than 3K (the only exception being `SPEfile.SPE` at 275K), which is smaller than most of our R functions.

This has the downside that in `test_read_BIN2R.R` we must download those files from github with lots of calls like:
```R
suppressWarnings(read_BIN2R(file = "https://github.com/R-Lum/Luminescence/raw/master/tests/testdata/BINfile_V3.bin",
                            txtProgressBar = FALSE))
```
I suggest adding `testdata` to the package, but excluding the `SPEfile.SPE` by listing it explicitly in `.Rbuildignore`. This will also allow the addition of a DRAC sample input (3.6K) for tests, and with that the package will increase by 32K at most.

**Comment by RLumSK** [comment]
What about using the package [vcr](https://cran.r-project.org/web//packages//vcr/index.html) for this?

**Comment by mcol** [comment]
That will add a Suggests dependency and it seems overkill as we are not trying to test http request as such, just trying to read some files that we also have locally (but CI won't have because they are not packaged).

That's not a big deal, I could leave things as they are and also download the DRAC input from github.

**Comment by RLumSK** [comment]
Agreed, then proceed with your original suggestion.

**Comment by mcol** [comment]
In order to make those files visible during tests, I'll move them from `tests/testdata` to `tests/testthat/data`, that seems the only way to make tests run reliably.
