### ISSUE TITLE
get_RLum.Analysis() - Grep elements by info element existence and value

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#18]
Extend method to allow for selecting elements by their info element existence and specific value. 

Problems: 
- Test for existence of any info element is needed (slot info might be empty)
- Test for existence of such element is needed (no element, no return)
- Unsolved issue: How the user get information on allowed elements?

BE CAREFUL. Any change in this method affects a lot of other functions

**Comment by RLumSK** [comment]
Should we move this to dev_0.8.0 or so?

**Comment by tzerk** [comment]
Actually, this was already implemented with 102ba03924316a1ff2c333646de1e1a2dea9a829, but the issue was not closed.
