### ISSUE TITLE
plot_GrowthCurve() - split function into separate functions

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#19]
Tasks:
- [ ] Split function into separate functions, e.g. `plot_DoseResponseCurve()` and `fit_DoseResponseCurve()`
- [ ] Return plots as separate output object element ,e.g. if `plot=FALSE` then no plot is shown, but an object containing the plot is returned like `a <- plot(test)`

**Comment by RLumSK** [comment]
Thisi not likely to be happen ... closing issue
