### ISSUE TITLE
deprecate/remove output.path argument from fit_CWCurve()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#207]
There's this TODO note:
https://github.com/R-Lum/Luminescence/blob/759a1142651cc557f9fd06c6b061d1aff244cdf9/R/fit_CWCurve.R#L224-L225

As now with more coverage we hit the lines where `output.path` is used and an output CSV file is generated, we get a note when running `R CMD check`:
```
 checking for detritus in the temp directory ... NOTE
  Found the following files/directories:
    ‘RtmpZkat2Ifit_CWCurve_Output_Default.csv’
```
So perhaps it's a good reason to actually remove that argument?

**Comment by RLumSK** [comment]
@mcol: Yes, I guess this is an ugly left-over before `RLum-class` object time. I suggest setting it to defunct directly and then we remove it in a version `1.x.x`.

**Comment by mcol** [comment]
I take that you mean to remove the code altogether and for the time being throw a warning if somebody were to set the argument, but just say if you meant something else.
