### ISSUE TITLE
Add citation section for individual functions

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#21]
The documentation of each function should contain a **Citation** section with a reference that can be used for more granular citation. The reference will follow the following style.

`<author1>, <author2> (<year>). "<function>: <title>". In: <RpackageAuthors>, (<year>): Luminescence: Comprehensive Luminescence Dating Data Analysis. R package version <version>. https://CRAN.R-project.org/package=Luminescence.`

**Comment by RLumSK** [comment]
From my point of view this is done, do you concur?

**Comment by tzerk** [comment]
Looks good, but the script fails to add a citation section if there is no reference section (e.g. `plot_KDE()`).

**Comment by RLumSK** [comment]
Ok, means we should add this section ...

**Comment by RLumSK** [comment]
Now ok?

**Comment by tzerk** [comment]
Perfect! Many thanks and: closed.
