### ISSUE TITLE
analyse_FadingMeasurement() - Add example

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#22]
Title says it all. Will probably require adding a new example data set to the package.

**Comment by RLumSK** [comment]
Sorry, I don't have such data yet ...

**Comment by RLumSK** [comment]
Ok, but where are the data? The file is missing.

**Comment by tzerk** [comment]
I added the data set first to my dev branch, and merged it only later with `dev_0.7.0`. Try checking out the latest 0.7.0 build, it should find the data.

**Comment by JohannesFriedrich** [comment]
It isn't there ...

**Comment by tzerk** [comment]
Now it should be... sorry, didn't think of `.gitignore` that prevented commiting the `.RData` file.

**Comment by JohannesFriedrich** [comment]
The examples to this data set work not as expected (error in the second to the last line):

    IR50_Age <- IR50_De / 7.00
> Error in IR50_De/7 : non-numeric argument to binary operator

**Comment by tzerk** [comment]
Fixed via the above commits.

**Comment by RLumSK** [comment]
So, its done I guess....
