### ISSUE TITLE
No interactive plots in plot_RLum.Data.Spectrum with plotly 4.5.2

### ISSUE THREAD

**Issue by JohannesFriedrich** [R-Lum/Luminescence#23]
In the function `plot_RLum.Data.Spectrum()` the argument `plot.type = "interactive"` gives an error. This is related to an update of the package `plotly`. With version 3.6.0 all works fine, but not with the recent one (4.5.2).

Example (from the manual):

    ##load example data
    data(ExampleData.XSYG, envir = environment())

     ##(4) interactive plot using the package plotly
     plot_RLum.Data.Spectrum(TL.Spectrum, plot.type="interactive",
          xlim = c(310,750), ylim = c(0,300), bin.rows=10,
          bin.cols = 1)

> Error: Variables must be length 1 or 85.
Problem variables: 'x'

**Comment by RLumSK** [comment]
Thanks and fixed!
