### ISSUE TITLE
remove the readxl dependency

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#237]
There are only 3 functions that now need to read an Excel file:
- `analyse_baSAR()`
- `use_DRAC()`
- `.import_ThermochronometryData()`

The idea is to remove support for input in Excel files and accept CSV files instead. This will allow us to remove `readxl` from our `Imports`.

**Comment by mcol** [comment]
@RLumSK Is it OK to work on `.import_ThermochronometryData()` or should I leave it for the time being?

**Comment by RLumSK** [comment]
... only if it does not change the output. Then yes, you can work on it (tests etc. for instance)
