### ISSUE TITLE
verbose option for calc_AliquotSize

### ISSUE THREAD

**Issue by JohannesFriedrich** [R-Lum/Luminescence#24]
Other `calc_...` functions like `calc_CentralDose()` already have a verbose option to show output on the terminal.

**Comment by tzerk** [comment]
Done.

**Comment by JohannesFriedrich** [comment]
Change the section `further reading` and write the LaTex command `\cr \cr` at the end of each line and not the beginning of the new one. I could not build the manual, when it is in the current layout. I used this and it worked:

#' \bold{Further reading} \cr\cr 
#' 
#' Chang, H.-C., Wang, L.-C., 2010. A simple proof of Thue's
#' Theorem on Circle Packing. \url{http://arxiv.org/pdf/1009.4322v1.pdf},
#' 2013-09-13. \cr\cr 
#' 
#' Graham, R.L., Lubachevsky, B.D., Nurmela, K.J.,
#' Oestergard, P.R.J., 1998.  Dense packings of congruent circles in a circle.
#' Discrete Mathematics 181, 139-154. \cr\cr
#' 
#' Huang, W., Ye, T., 2011. Global
#' optimization method for finding dense packings of equal circles in a circle.
#' European Journal of Operational Research 210, 474-481. \cr\cr

**Comment by tzerk** [comment]
Should be working now on `dev_0.7.0`, no warnings/errors with our custom build script. Please double-check and close if fixed.

**Comment by RLumSK** [comment]
I also cannot verify this, it should be not an issue.

**Comment by JohannesFriedrich** [comment]
verbose option also possible for `calc_CosmicDoseRate()`?

**Comment by tzerk** [comment]
Done.
