### ISSUE TITLE
clean ups in RejectionCriteria returned from analyse_SAR.TL()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#245]
As part of #147, I'm having a detailed look at what `analyse_SAR.TL()` produces and returns. One of this is the `rejection.criteria` data frame, which is sometimes produced incorrectly.

Example:
```R
data(ExampleData.BINfileData, envir = environment())
object <- Risoe.BINfileData2RLum.Analysis(TL.SAR.Data, pos = 3)

analyse_SAR.TL(
        list(object, object),
        signal.integral.min = 210,
        signal.integral.max = 220,
        dose.points = 1:7,
        integral_input = "temperature",
        sequence.structure = c("SIGNAL", "BACKGROUND"))

res@data$rejection.criteria
#             citeria value threshold status
# 1 recuperation rate    NA   +/- 0.1   <NA>   # recycling ratio
# 2 recuperation rate    NA       0.1     OK
# 3 recuperation rate    NA   +/- 0.1   <NA>   # recycling ratio
# 4 recuperation rate    NA       0.1     OK
```
In these lines of code:
https://github.com/R-Lum/Luminescence/blob/be1602b2c80944541e8386917628e9019143d1af/R/analyse_SAR.TL.R#L352-L359

- Typo: "citeria" instead of "criteria", but actually "criterion" would be better, as the other column names are singular
- Since `RecyclingRatio` is `NA`, `colnames(RecyclingRatio)` is `NULL`, so we get that "recuperation rate" is printed in all the rows (due to R doing recycling the non-null element in the vector): I would make it write "recycling ratio" when `RecyclingRatio` is `NA`
- The docs say that for `rejection.criteria` `NA` is produced if no `R0` dose point exists, but that's not the case, as the above data frame is generated
- The "status" column actually reports ` 0.1` (with a space) rather than `0.1` due to the `paste("")` term
- Bonus: the `+/-` could be replaced with the unicode symbol `±` if desired

In these other lines:
https://github.com/R-Lum/Luminescence/blob/be1602b2c80944541e8386917628e9019143d1af/R/analyse_SAR.TL.R#L369-L370
- While value is `NA` in all cases, in the "recycling ratio" cases the status is `NA`, but for "recuperation rate" the status is `OK`: I suppose it should be `NA` in all cases, but perhaps that difference in treatment was intentional?

**Comment by RLumSK** [comment]
I do agree with the suggested changes, thank you!

**Comment by mcol** [comment]
One additional thing: for recuperation rate we report the rejection criteria divided by 100 (line 358), but we don't divide in the actual test where we set the status (lines 369-370). For recycling ratio we divide in both places, so I expect that the same would be correct for recuperation rate too.

This means that until now recuperation rates have been marked OK in more cases than expected.

**Comment by RLumSK** [comment]
OK, obviously this also needs a fix
