### ISSUE TITLE
curve normalisation in plot_RLum.Data.Curve()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#250]
There is a discrepancy between docs and code concerning argument `norm` of `plot_RLum.Data.Curve()`:
- the code accepts either a logical or a character, one of 'max', 'last' or 'huot'
- the docs allow a logical or a character, one of 'max', 'min' or 'huot' (in details 'last' is mentioned but not 'min')

First of all, I'll add the 'last' option to the docstring for `norm`.

`norm = "min"` is actually used in the function tests, but if a user specifies it no normalisation occurs. If this the expected behaviour? Whatever it is, it should be documented.

**Comment by RLumSK** [comment]
Sorry for the delay, I think `min` does not make sense, it should be  `c('max', 'last', 'huot')`
