### ISSUE TITLE
remove calc_Kars2008()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#252]
This function has been deprecated in favour of `calc_Huntley2006()` since March 2018 (version 0.8.1). Any reason to keep it?

**Comment by RLumSK** [comment]
No, please set it to defunct (but not remove it yet)

**Comment by mcol** [comment]
This is all there is in that function (excluding docs):
https://github.com/R-Lum/Luminescence/blob/053a1c56fd6d0d21447babf4e75048fb8ac30f0e/R/calc_Kars2008.R#L88-L91

Should I leave things as they are? Or just remove the docs? Or something else?

**Comment by RLumSK** [comment]
Good point, please remove the documentation and set it to defunct. Thanks.
