### ISSUE TITLE
recover coverage in analyse_pIRIRSequence.R

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#253]
Some of the recent fixes have caused a loss of ~180 lines of coverage (from 87.5% to 37.5%) in `analyse_pIRIRSequence.R`. I didn't see anything obvious why we are seeing that massive change, but we should try to find a test that help us recover the previous coverage.

**Comment by mcol** [comment]
The loss in coverage is due to 4a693e40edb3a07ce23fb9764e203b40326d8d18, as now no plotting occurs with our tests.

Looking at that change, it's perhaps too restrictive. If a user sets `plot.single = FALSE`, we shouldn't worry about the size of the plot area, as each plot will be on its own. Would that be acceptable?

**Comment by RLumSK** [comment]
Yes, if it is single the plot area does not matter, thanks, this should be corrected.
