### ISSUE TITLE
analyse_SAR.CW.OSL() - Ambiguous rejection criteria units

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#26]
As far as I can see the rejection criteria in `analyse_SAR.CW.OSL()` are calculated as a **ratio** before comparing them to the provided list of threshold values. But it is unclear whether the user should provide a **ratio** or a **percentage** as threshold value.

For `recycling.ratio, testdose.error` and `palaeodose.error` the user is required to provide a percentage, but for `recuperation.rate` it is a ratio.

My suggestion are as follows:

1. have the user also specify a percentage for `recuperation.rate`
2. Update the documentation for the argument `rejection.criteria` and in the details, clearly stating that percentage values are assumed
3. check and make sure that in the output table the calculated values and thresholds have the same unit

At the moment, the examples are "wrong" in the sense that it provides a `recuperation.rate` of 10. In code line 855 

```r 
if(Recuperation[x] > rejection.criteria$recuperation.rate){
```

this value is compared against a ratio.

**Comment by RLumSK** [comment]
Done and thanks!
