### ISSUE TITLE
use_DRAC() - assign correct class to output elements

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#27]
It appears that the numerical values returned from DRAC are by definition of type 'factor', but 
they should be of type 'numeric' is this a feature or a bug?

**Comment by tzerk** [comment]
Just checked, they are neither of class `numeric` nor `factor`, but of `character`. Do you mean any specific data output (`$highlights, $input, $output`)? Either way, it is certainly not a feature or a bug. The function simply misses a type conversion after the output is read from the POST response, which I could add if there is demand.

**Comment by RLumSK** [comment]
Ok, can you please add it? If one want to proceed with the data this can cause troubles.
