### ISSUE TITLE
set_RLum() - Sanitize originator

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#30]
**Situation**: 
When creating an RLum-Object without specifying the \@orginator the latter will automatically be set by 

```r
originator <- as.character(sys.call(which = -1)[[1]])
```

**Problem**: 
When a function in the package is called explicitly (i.e., `package::function`) the originator becomes `NA`.

**Reproducible example:**
```r
library(Luminescence)
data(ExampleData.DeValues, envir = environment())
res <- Luminescence::calc_CentralDose(ExampleData.DeValues$CA1)
print(res@originator)
```

**Proposed fix:**
Check if `as.character(sys.call(which = -1)[[1]])` contains double colons (`::`) and only take anything following it.

**Comment by RLumSK** [comment]
Please check the bugfix, my own tests worked well ... however ...

**Comment by tzerk** [comment]
Seems fine to me, thanks!
