### ISSUE TITLE
calc_CentralDose() ... a few bugs

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#302]
**Describe the bug**

This dataset 
```r
     De ERR_DE
1 -0.56  -0.15
2 -0.16  -0.10
3  0.00   0.12
4  0.04     NA
```

with

```{r
calc_CentralDose(
  data = df, 
  log = FALSE)
```

returns

```
Error in sig/delta : non-numeric argument to binary operator
```

for 

```{r}
calc_CentralDose(
  data = df, 
  log = TRUE)
```

It returns a warning without context: 

```
In log(data$ED) : NaNs produced
```

In all cases the error should be caught earlier and with meaningful messages.

**Comment by mcol** [comment]
By default this function uses `na.rm = FALSE`, and by setting it to true, the error goes away, although we get warnings for the removed `NA`s (I think these should be just messages, as the user has explicitly asked for it and it's the sensible thing to do).

Perhaps we should warn if `na.rm = FALSE` but the data contains missing values?

I'll continue chasing the error, but I'm one stop away from home. :rocket:

**Comment by mcol** [comment]
If `na.rm = FALSE`, the `NA` in the data frame very quickly extends to all other expressions (for example, after operations such as `sum(wu * yu)`). After `sig <- try(seq(sig0, sig1, sig1 / 1000), silent = TRUE)`, `sig` is of class `try-error`, but the function carries on anyway, until it reaches
```R
if(!log)  sig <- sig / delta
``` 
which is where the "Error in sig/delta : non-numeric argument to binary operator" gets printed.

I think it doesn't make sense to run this function with `na.rm = FALSE`: we should at least change the default to `TRUE`, but probably we should always remove the missing values like we do somewhere else. Given that the function needs to sums over all data, I can't see a case where leaving `NA`s in the dataset is a good idea.

**Comment by RLumSK** [comment]
Then I suggest that the function removes `NA` values automatically with a warning, this is probably the best way. The other point is that, by definition, the uncertainty cannot be < 0. So I suggest running `abs()` silently over the dataset.
