### ISSUE TITLE
CI: Input 'save-always' has been deprecated

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#305]
The following warnings have started appearing in the Actions pages:

> Warning: Input 'save-always' has been deprecated with message: save-always does not work as intended and will be removed in a future release.
> A separate `actions/cache/restore` step should be used instead.
> See https://github.com/actions/cache/tree/main/save#always-save-cache for more details.

Currently they seem totally harmless.

**Comment by RLumSK** [comment]
OK

**Comment by mcol** [comment]
I don't see this anymore in our logs, it may have been fixed by https://github.com/r-lib/actions/pull/934.

**Comment by RLumSK** [comment]
@mcol OK, thanks!
