### ISSUE TITLE
problems in plot_GrowthCurve()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#307]
In preparation for #141 I'm looking at `plot_GrowthCurve()` with greater attention. These are things I'd like to solve beforehand:
- (1) The docs for `sample` are probably out of date as they reference 4 column (3 mandatory and 1 optional), but that contradicts the actual code:
  https://github.com/R-Lum/Luminescence/blob/1b1183bb1e8da9875abea1c1bb0ef5a456717b7b/R/plot_GrowthCurve.R#L95-L98
  https://github.com/R-Lum/Luminescence/blob/1b1183bb1e8da9875abea1c1bb0ef5a456717b7b/R/plot_GrowthCurve.R#L343-L346
 
- (2) There's once case of a mode that doesn't appear anywhere else:
  https://github.com/R-Lum/Luminescence/blob/1b1183bb1e8da9875abea1c1bb0ef5a456717b7b/R/plot_GrowthCurve.R#L1849-L1850

- (3) There's some mismatch between these two checks (which should actually be consolidated if possible), in that the first one also includes QDR and GOK, but the second doesn't:
  https://github.com/R-Lum/Luminescence/blob/1b1183bb1e8da9875abea1c1bb0ef5a456717b7b/R/plot_GrowthCurve.R#L340-L341
  https://github.com/R-Lum/Luminescence/blob/1b1183bb1e8da9875abea1c1bb0ef5a456717b7b/R/plot_GrowthCurve.R#L520-L525

- (4) It seems that a few blocks of code can be quite easily consolidated among the various fitting methods.

**Comment by RLumSK** [comment]
Hi @mcol, briefly:

1. Yes, this is actually wanted to not further confuse the user, but you are right, the documentation is not correct in that records
2. This "regeneration" is a left over, and it should be "interpolation". Thanks for spotting this. 
3. This was a hot fix because the non-linear-sequare fit was not working as expected, yes, it should be consolidated in a sense that `LIN` and `QDR` can work with just two points
4. I do agree.

**Comment by mcol** [comment]
> 3\. This was a hot fix because the non-linear-square fitting was not working as expected, yes, it should be consolidated in a sense that `LIN` and `QDR` can work with just two points
What should happen then, should we stop or a warning is sufficient? It seems that originally there was only the second block (warning), then you added the stop in a85f441. Running the tests doesn't reveal any problems if we just raise a warning, but perhaps you were working on some data that made you think that that was not enough?

**Comment by mcol** [comment]
Here we are in the QDR method with MC, and I find it suspicious that in the extrapolation case we always use `y = 0` instead of `y = data.MC.De[i]` like we do in the interpolation block:
https://github.com/R-Lum/Luminescence/blob/24be41077249eb26a63db4c003b44847dbcd5aae/R/plot_GrowthCurve.R#L654-L676
Is that intentional?

**Comment by mcol** [comment]
Mmm, actually looking at what happens in the non-MC case this may be fine, but double-checking doesn't hurt.
