### ISSUE TITLE
calc_TLLxTxRatio: wrong error calculation

### ISSUE THREAD

**Issue by Eiskeil** [R-Lum/Luminescence#31]
This function currently uses an invalid way of error calculation for the Lx/Tx ratio. For instance, when the integrated background counts are the same for Lx and Tx, the value for Tx will be zero.

**Comment by RLumSK** [comment]
Please check whether this works for you

**Comment by JohannesFriedrich** [comment]
This solution just changed the situation, when LnLx.BG = TnTx.BG. In dev_0.7.0_JF we added a new calculation for the error for LxTx, following Duller 2007, Ancient TL 25.

**Comment by RLumSK** [comment]
...ok as talked about ... please check this with the @Eiskeil

**Comment by Eiskeil** [comment]
Function should be ok now.

**Comment by RLumSK** [comment]
In which version? The version based on Duller 2007 cannot be applied ...

**Comment by RLumSK** [comment]
@Eiskeil and @JohannesFriedrich: Please report a solution, otherwise I will revoke the changes before the CRAN submission.

**Comment by JohannesFriedrich** [comment]
@RLumSK  You can revoke the solution presented in dev_0.7.0_JF. We have to decide about another approach for calculation the error, but not in version 0.7.0.

**Comment by RLumSK** [comment]
Currently not longer an issue. Ticket closed.
