### ISSUE TITLE
design of plot_GrowthCurve()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#319]
As of #318 `plot_GrowthCurve()` is a relatively small function that is devoted to plotting. However, it still does the fitting by calling `fit_DoseResponseCurve()`. However, perhaps a better design could be to accept an object produced by `fit_DoseResponseCurve()`, so that no fitting happens inside it.

If that's a sensible direction to take, we need to rework a bit what `fit_DoseResponseCurve()` produces, because not all that is required for plotting can be retrieved from the fit object. For example, the function uses the actual data that was used in fitting, so we need to have this code:

https://github.com/R-Lum/Luminescence/blob/b6027a92e9b4d556c998ff1432147d13983b35f2/R/plot_GrowthCurve.R#L196-L200

This makes `plot_GrowthCurve()` a bit messy and potentially fragile, as it has to implement operations that have already been done quite thoroughly when fitting (code duplication).

As already mentioned in https://github.com/R-Lum/Luminescence/pull/318#issuecomment-2414899338, it would also be nice to rework the arguments a bit:
- `output.plot` is now unnecessary and should be removed
- `output.plotExtended` and `output.plotExented.single` should be renamed to `plotExented` and `plotExented.single` (or something else)

Something to consider in the overall design is this: what should a function (such as `analyse_SAR.CWOSL()`) that now calls `plot_GrowthCurve()` do if we were to create a stronger fit/plot separation?
https://github.com/R-Lum/Luminescence/blob/b6027a92e9b4d556c998ff1432147d13983b35f2/R/analyse_SAR.CWOSL.R#L1224-L1232

**Comment by RLumSK** [comment]
Agreed, every function should produce `RLum.Results` object, so `fit_DoseResponseCurve()`; exception might be `plot_DoseResponseCurve()` because here such object does not make sense ... let's see.

**Comment by mcol** [comment]
From https://github.com/R-Lum/Luminescence/pull/318#issuecomment-2415887892:

> Thanks @mcol: My suggestion: Move the code to plot_DoseReponseCurve() for plotting and keep the plot_GrowthCurve() as a wrapper only (for the moment) that way there is no need to touch other functions and both functions can be improved gradually. Regarding the arguments:
> 
>     * `output.plot` -> `plot`
> 
>     * `output.plotExtended` -> `plot_extended`
> 
>     * `output.plot` -> `plot_single`

**Comment by RLumSK** [comment]
> As of #318 `plot_GrowthCurve()` is a relatively small function that is devoted to plotting. However, it still does the fitting by calling `fit_DoseResponseCurve()`. However, perhaps a better design could be to accept an object produced by `fit_DoseResponseCurve()`, so that no fitting happens inside it.
> 
> If that's a sensible direction to take, we need to rework a bit what `fit_DoseResponseCurve()` produces, because not all that is required for plotting can be retrieved from the fit object. For example, the function uses the actual data that was used in fitting, so we need to have this code:
> 
> https://github.com/R-Lum/Luminescence/blob/b6027a92e9b4d556c998ff1432147d13983b35f2/R/plot_GrowthCurve.R#L196-L200
> 
> This makes `plot_GrowthCurve()` a bit messy and potentially fragile, as it has to implement operations that have already been done quite thoroughly when fitting (code duplication).
> 
> As already mentioned in [#318 (comment)](https://github.com/R-Lum/Luminescence/pull/318#issuecomment-2414899338), it would also be nice to rework the arguments a bit:
> 
> * `output.plot` is now unnecessary and should be removed
> * `output.plotExtended` and `output.plotExented.single` should be renamed to `plotExented` and `plotExented.single` (or something else)
> 
> Something to consider in the overall design is this: what should a function (such as `analyse_SAR.CWOSL()`) that now calls `plot_GrowthCurve()` do if we were to create a stronger fit/plot separation?
> 
> https://github.com/R-Lum/Luminescence/blob/b6027a92e9b4d556c998ff1432147d13983b35f2/R/analyse_SAR.CWOSL.R#L1224-L1232

The call `fit_DoseResponseCurve()` and the `plot_DoseResponseCurve()` later in the plot section.

**Comment by RLumSK** [comment]
> As of #318 `plot_GrowthCurve()` is a relatively small function that is devoted to plotting. However, it still does the fitting by calling `fit_DoseResponseCurve()`. However, perhaps a better design could be to accept an object produced by `fit_DoseResponseCurve()`, so that no fitting happens inside it.
> 
> If that's a sensible direction to take, we need to rework a bit what `fit_DoseResponseCurve()` produces, because not all that is required for plotting can be retrieved from the fit object. For example, the function uses the actual data that was used in fitting, so we need to have this code:
> 
> https://github.com/R-Lum/Luminescence/blob/b6027a92e9b4d556c998ff1432147d13983b35f2/R/plot_GrowthCurve.R#L196-L200
> 
> This makes `plot_GrowthCurve()` a bit messy and potentially fragile, as it has to implement operations that have already been done quite thoroughly when fitting (code duplication).
> 
> As already mentioned in [#318 (comment)](https://github.com/R-Lum/Luminescence/pull/318#issuecomment-2414899338), it would also be nice to rework the arguments a bit:
> 
> * `output.plot` is now unnecessary and should be removed
> * `output.plotExtended` and `output.plotExented.single` should be renamed to `plotExented` and `plotExented.single` (or something else)
> 
> Something to consider in the overall design is this: what should a function (such as `analyse_SAR.CWOSL()`) that now calls `plot_GrowthCurve()` do if we were to create a stronger fit/plot separation?
> 
> https://github.com/R-Lum/Luminescence/blob/b6027a92e9b4d556c998ff1432147d13983b35f2/R/analyse_SAR.CWOSL.R#L1224-L1232

Not necessarily, because it makes even sense to call a plot function with `plot = FALSE` if it calculates something for the plot the user may want to use. Here, to be honest, I am uncertain, I have to look again into the code for a longer time. Therefore I suggest to focus on the `fit_DoseResponseCurve()` first.
