### ISSUE TITLE
Update documentation using Markdown 

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#32]
With the release of  `roxygen2`, the package  documentation can be created using markdown tags. 
The documentation should be updated accordingly to account for this new development. 

- [x] calc_Fun()
- [x] analyse_Fun()
- [x] plot_Fun()
- [x] convert_Fun()
- [x] ... everything else

**Comment by tzerk** [comment]
Was quite the work, but I think the much better readability of the files was worth it. Anyway, everything was merged in `dev_0.8.0` and there were no errors (yet). Closed.
