### ISSUE TITLE
fit_DoseResponseCurve()

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#323]
Apparently the repeated definition of the function `De.fs` with different arguments
leads to the following build note: 

```
  fit_DoseResponseCurve: multiple local function definitions for ‘De.fs’
    with different formal arguments

```

I looked up the code but I don't have an immediate solution to it.

**Comment by mcol** [comment]
I'm not sure how the `...` will be interpreted by `uniroot()`. I'll just make the argument list identical in all definitions for the time being.
