### ISSUE TITLE
use seek() to advance in a connection in read_BIN2R()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#334]
We could use `seek()` instead of `readBin()` when we just want to advance in the file. In those cases we currently read the content and assign it to a variable (often called `STEPPING`). It's not clear that it brings any visible speed improvement, but in theory it should be better.

One thing to mention, however, is this passive-aggressive message in `seek()`'s docs:

> Use of ‘seek’ on Windows is discouraged.  We have found so many
> errors in the Windows implementation of file positioning that
> users are advised to use it only at their own risk, and asked not
> to waste the R developers' time with bug reports on Windows'
> deficiencies.

Some online searches seem to disagree with that statement, but I don't have direct experience with it. We already have one usage of `seek()`, albeit very minor:
https://github.com/R-Lum/Luminescence/blob/b3373aa522f17a13ae727b18d1e64642474c497f/R/read_BIN2R.R#L1132-L1134

Perhaps we could try on CI and see what happens?

**Comment by RLumSK** [comment]
Ah, OK, I think that then I have tried this already. But we can implement our own stepping. Because if we have only one large raw vector of all data, we know where to expect which byte.

**Comment by mcol** [comment]
Sure, if we do that then we don't need `seek()`. That work is quite invasive, so I'm first trying to clean up other parts that seem lower-hanging fruits.
