### ISSUE TITLE
uses of length(*_SIZE)>0 in read_BIN2R()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#338]
There are a few instances like this:

https://github.com/R-Lum/Luminescence/blob/b3373aa522f17a13ae727b18d1e64642474c497f/R/read_BIN2R.R#L700-L707

It looks suspicious that we check for `length(FNAME_SIZE) > 0` rather than `FNAME_SIZE > 0`. In the `readBin()` call we read 1 byte, so I can't see how `FNAME_SIZE` could not have length 1. Coverage analysis shows that indeed the `else` branch is never hit.

**Comment by RLumSK** [comment]
@mcol Good point, this has something to do how the string is constructed (or at least was in the past) this was some kind of Pascal like encoding where the first byte tells about the length of the rest of the string. However, if I am not mistaken in later versions they abolished this and the size did not matter more.

**Comment by mcol** [comment]
Strings are still in Pascal format. What I've seen in our code, is that in a couple of cases (for date and time) we override the declared size.
