### ISSUE TITLE
correct warning from analyse_pIRIRSequence() and restore coverage

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#349]
Commit 048c3bc99eab9fa283d33227bd47c60d4a5528ba fixed my misunderstanding of the `plot.single` option (I always get confused about what it means). However, also the warning message and what I had written in `NEWS` should reflect the correct use of that option. 

That commit also caused a sizeable drop in coverage, which I hope to be able to restore by adding a new test.

**Comment by RLumSK** [comment]
@mcol I do agree, the argument was never really well chose. Perhaps we should rename it to `plot_singlePanels`? I had implemented this to wrap existing plots and plot functions where the comprehensive plot is not wanted but only single panels that can be rearranged.

**Comment by mcol** [comment]
Renaming arguments will break a lot of uses. We could start thinking about that, I've opened #351 to track that.
