### ISSUE TITLE
rename the plot.single argument

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#351]
I find `plot.single` confusing, as I can never remember if it means to put all plots on a single page (wrong) or if it means that each plot is done on its own (correct).  See also https://github.com/R-Lum/Luminescence/issues/349#issuecomment-2437136692. 

Note that we also have `plot_single` and `output.plot.single`.

**Comment by RLumSK** [comment]
@mcol We can unify stuff, means, `output.plot.single` can be renamed to whatever we decide to go for.
