### ISSUE TITLE
merge_RLum.Data.Spectrum() ... new methods analogue to merge_RLum.Data.Curve() 

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#368]
We have a merge method for `RLum.Data.Curve()` + corresponding S3 generics that allows us to merge curve data very conveniently, such as: 

```r
c1 <- set_RLum("RLum.Data.Curve")
c2 <- set_RLum("RLum.Data.Curve")
c1 + c2 
c1 - c2
```
such set of methods does not exist yet for `RLum.Data.Spectrum()` objects. To implement this feature we have to: 

- [x] write a new function `merge_RLum.Data.Spectrum()` analogue to `RLum.Data.Curve()`; perhaps this two things can be even merged in same way in a new `merge_RLum.Data()`
- [x] Add this function to the option in `merge_RLum()`
- [x] Add corresponding methods in `methods_RLum.R`
- [x] Add test cases
- [x] Add NEWS

## More

If this is done, we should explore (not yet implement) this feature for `RLum.Data.Image()` as well.

**Comment by mcol** [comment]
@RLumSK `merge_RLum.Data.Curve()` supports these merge methods, are they all meaningful for spectra?
- mean, median, sum, sd, var, max, min, append, -, *, /

**Comment by mcol** [comment]
We have discussed this a bit further:
- objects of different sizes cannot be merged
- row names must match exactly
- if column names report temperature, then these must match (with some small differences allowed)
- append is fine, in which case we add the additional columns, and it will be up to the plotting functions to deal with non-monotone column names
