### ISSUE TITLE
 install_DevelopmentVersion() ... fails while working behind a proxy

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#37]
This function fails to work if called from behind a proxy which requires a  username and password combination. In such cases the call

`devtools::install_github("R-Lum/Luminescence@master")`

fails as well. An option (further arguments) would be needed to deal with this challenge.

**Comment by tzerk** [comment]
Currently not on a computer, but as I reminder for myself I will leave the following link:

http://stackoverflow.com/questions/17783686/solution-how-to-install-github-when-there-is-a-proxy

Should be easy enough add new arguments to pass to httr.

**Comment by tzerk** [comment]
Unable to reproduce due to a lack of a private proxy. Also, this is not a problem of the package itself. A possible solution presented in the link above may be to run

```r
library(httr)
set_config(
  use_proxy(url="18.91.12.23", port=8080, username="user",password="password")
)
```

prior to calling `devtools::install_github()`, or `Luminescence::install_DevelopmentVersion()` for that matter.
