### ISSUE TITLE
plot_RLum.Data.Spectrum() - wavelength colour ramp

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#371]
The function uses a colour ramp that does not seem to be always assigned consistently. It needs some investigation. ّI will drop a dataset in the heiBOX.

**Comment by mcol** [comment]
In the example the colours are indeed messed up!
![img_371](https://github.com/user-attachments/assets/8c2375d2-0897-49fe-b11e-e80e90f84a38)

I've now been able to produce this sort of gradient:
![img-371-b](https://github.com/user-attachments/assets/31d05980-59b9-4551-8f44-2e66f7e5d2c6)
