### ISSUE TITLE
 analyse_IRSAR.RF() .... performance issue for vertical sliding

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#372]
The sliding takes quite some time and the underlying code should be optimised for performance.

* Currently the example in the heiBOX takes ca. 13 s on my machine, the underlying C++ code is here: https://github.com/R-Lum/Luminescence/blob/master/src/src_analyse_IRSARRF_SRS.cpp

## More

Please also check the bug when the code is run as follows: 

```r
results <- analyse_IRSAR.RF(
  object = temp,
  method = "VSLIDE",
  main = as.list(paste0(SAMPLE_ID, " | MAIN")),
  RF_nat.lim = 2,
  method.control = list(vslide_range = 'auto', cores = 4))
```

it returns `Error: [analyse_IRSAR.RF()] 'method.control' should be of class 'list'
This should not happen and is somewhat related to the recent changes.

**Comment by mcol** [comment]
There are a couple of things in the current sliding algorithm that can be quite easily improved and produce quite significant savings:

1. At the start of `sliding()` we create a list of 10 windows of growing size: I still don't fully see what looking at a small window (always centered in the middle of the slide range) contributes over looking at the entire range in one go. In any case, by creating a smaller number of window sizes, we can do way less work. I have the feeling that 3-4 windows may suffice, but we could add a `method.control` option to let a user set a higher value if they feel that the fit is not good enough. 
2. The sizes of windows created seems suboptimal. For example, this is what gets generated on the heiBOX example:
    ```
     min.idx  max.idx     size
      593207   593209        3
      527296   659120   131824
      461384   725032   263648
      395472   790944   395472
      329560   856856   527296
      263648   922768   659120
      197736   988680   790944
      131824  1054592   922768
       65912  1120504  1054592
           0  1186415  1186416
    ```
    The first window is actually useless (at least it's super fast), we could start with a larger first window. On its own, this will not improve the performance, but if we go with fewer windows it will have a positive impact on the solution quality (as it will actually do some search in the first window).

Here are some timings on single core according to optimization level:

| num.windows | -O3 | -O2 |
|-----:|-------:|------:|
|10  |  29.1 | 40.9 |
| 5   | 15.5 | 21.2 |
| 3   | 10.1 | 13.5 |

The solution is effectively identical in all cases.

**Comment by mcol** [comment]
I think this is enough for now, we may revisit it in the future if we come up with a new algorithm.
