### ISSUE TITLE
warning from merge_RLum.Data.Curve(..., merge.method = "append")

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#377]
This example generates an undesired warning:
```R
data(ExampleData.XSYG, envir = environment())
TL.curves  <- get_RLum(OSL.SARMeasurement$Sequence.Object, recordType = "TL (UVVIS)")
merge_RLum.Data.Curve(list(TL.curves[[1]], TL.curves[[3]]),  merge.method = "append")
# Warning message:
# In (0L:(length.out - 1L)) * by :
#   longer object length is not a multiple of shorter object length
```

**Comment by RLumSK** [comment]
The warning should not happen, obviously something is not considered sufficiently. It appears somewhat here: 

```r
  if (merge.method[1] == "append" & length(unique(diff(object[[1]]@data[,1])))) {
      step <- unique(diff(object[[1]]@data[,1]))
      newx <- seq(from = min(object[[1]]@data[,1]), by = step, length.out = sum(check.length))
      temp.matrix <- cbind(newx, temp.matrix)
```

**Comment by mcol** [comment]
This part of the `if` doesn't seem to make much sense, since it's an integer and it will always be true (as it's impossible to create an `RLum.Data.Curve` with `data = NULL` or `numeric(0)`, at least with `set_RLum()`):
```R
length(unique(diff(object[[1]]@data[,1])))
```

In any case, the warning is generated because we don't have a unique step, due to some numerical imprecision:
```R
step
0.0999999999999943 0.0999999999999979 0.0999999999999996 0.0999999999999999
                 1                  1                  1                  1
               0.1  0.100000000000001  0.100000000000009
                 4                  2                  1
```
That must be why elsewhere we are using `round(..., 1)`.

**Comment by RLumSK** [comment]
@mcol: No, we do not round the raw data, they come in as-is. But I do agree that the `length()` statement does not make much sense. Please check the comment in the code above those lines where I have tried to detailed why we are doing what we are doing.

**Comment by mcol** [comment]
We round the difference between x-values:
https://github.com/R-Lum/Luminescence/blob/52a1cc0816292785d63bc8a343d9a3a52142303e/R/merge_RLum.Data.Curve.R#L164-L165
