### ISSUE TITLE
Wrong wavelength scale in plot_RLum.Data.Spectrum

### ISSUE THREAD

**Issue by JohannesFriedrich** [R-Lum/Luminescence#39]
A wrong wavelength scale appears within the Luminescence 0.7.3 package when executing example nr. 4 from the documentation of `plot_RLum.Data.Spectrum`:

    data(ExampleData.XSYG, envir = environment())

    plot_RLum.Data.Spectrum(TL.Spectrum, plot.type="interactive",
     xlim = c(310,750), ylim = c(0,300), bin.rows=10,
     bin.cols = 1) 

`xlim` works, but has wrong labels. 
In contrast to issue #23 the bug is within the Luminescence package, because with changing to older versions of plotly the error remains, but disappears when changing the Lumi-package to 0.6.4.

**Comment by RLumSK** [comment]
It has nothing to do with `xlim`, but with `bin.rows`. I'll check this.

**Comment by JohannesFriedrich** [comment]
Even with the default values of `bin.rows = 1`, `bin.cols = 1` and no specific `xlim`-value a wrong scale appears.

**Comment by RLumSK** [comment]
Actually, the labelling is not correct, but the plot is. Unfortunately plotly does not consider the matrix labelling.

**Comment by JohannesFriedrich** [comment]
Thanks!
