### ISSUE TITLE
analyse_FadingMeasurement() main header shows "expression("

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#390]
**Describe the bug**
The header of the plot output shows "expression()" while this should not be shown 
at all but we should just see the subscript.

<img width="793" alt="Screenshot 2024-11-05 at 18 26 32" src="https://github.com/user-attachments/assets/52dc336e-5190-49df-b20e-27dfa2539f5e">

**Comment by mcol** [comment]
It's probably due to 1ba40def4, but none of the plots in the tests show that behaviour. How can I reproduce that plot?

**Comment by RLumSK** [comment]
Still the same for me. Somehow `expression()` is evaluated by also printed. Probably in combination with `bquote()` there is a problem. 

This does not work: 
```r
plot(1:10, main = bquote(expression(L[x])))
```

But this does work: 

```r
plot(1:10, main = bquote(L[x]))
```
