### ISSUE TITLE
many checks in analyse_IRSAR.RF() for method = "SLIDE" don't consider "VSLIDE"

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#396]
There are some occurrences where some code is performed if `method = "SLIDE"`, but presumably they apply also for `method = "VSLIDE"`:
https://github.com/R-Lum/Luminescence/blob/38070b9c61a9465dcd7caf5617cdc7441a99b519/R/analyse_IRSAR.RF.R#L535-L537
https://github.com/R-Lum/Luminescence/blob/38070b9c61a9465dcd7caf5617cdc7441a99b519/R/analyse_IRSAR.RF.R#L727-L729
https://github.com/R-Lum/Luminescence/blob/38070b9c61a9465dcd7caf5617cdc7441a99b519/R/analyse_IRSAR.RF.R#L742-L744
@RLumSK Should these be applied in both sliding methods?

**Comment by RLumSK** [comment]
They do, indeed, thanks for noticing this.
