### ISSUE TITLE
Unclear computation of algorithm_error

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#400]
This code seems wrong:
https://github.com/R-Lum/Luminescence/blob/50579fe95ba6812b8f08f1bff726a703fb7ea29a/R/analyse_IRSAR.RF.R#L1051-L1055

Note that some data is put into a matrix, then the top-left element `[1, 1]` is returned, and its `sd()` computed: ~~as there's just one element,  it returns 0, and from inspection I think that this is always the case.~~

@RLumSK Do you know what this should be doing instead?

**Comment by mcol** [comment]
Actually, if `temp_vslide_indices` has multiple elements, we'll get multiple values, so the `sd()` calculation seems valid. Taking only the top-left elements still looks suspicious.

**Comment by RLumSK** [comment]
@mcol I cannot tell from the top of my head, it would require a more deeper investigation, if you cannot solve it, I will have a look at it next week.

**Comment by RLumSK** [comment]
@mcol: I had another look, it makes sense, because we want to have the offset of the t_n values and see how much it varies. This defines a systematic error of some kind. Means, the code is valid.

**Comment by mcol** [comment]
Thanks for double-checking! If only the first offset is required, why are we building an entire matrix? Just using `RF_nat[1, 1] + temp.sliding.step` will produce the same result, without the confusing (and memory-inefficient) matrix setup. I've tested it by computing that quantity both ways and asserting that they are equal, using our tests and the heiBOX example. I'll post a patch for that.
