### ISSUE TITLE
analyse_SAR.CWOSL() - Coherent output table style

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#42]
Suppose we have a SAR measurement with 2 aliquots.

Currently, the output table `<obj>@data$rejection.criteria` has the following structure:

Criteria | Value | Threshold | Status
--------|--------|------------|-------
Recycling ratio (R5/R1)| 1.047900e+00   |    0.1   |  OK
Recycling ratio (R6/R1) |1.111200e+00   |    0.1 | FAILED
Recuperation rate |1 7.020000e-02    |   0.1   |  OK
Testdose error |4.171923e-02   |    0.1   |  OK
Palaeodose error |1.254600e-01    |   0.1 |FAILED
De > max. dose point |4.355200e+02   |  730.0 |   OK
Recycling ratio (R5/R1) |1.423800e+00   |    0.1| FAILED
Recycling ratio (R6/R1) |1.546100e+00    |   0.1 | FAILED
Recuperation rate 1 | 9.100000e-02    |   0.1  |   OK
Testdose error |1.639996e-01    |   0.1 |FAILED
Palaeodose error |3.276400e-01    |   0.1 |FAILED
De > max. dose point |5.640700e+02   |  730.0    | OK

This means that there a 6 rows for each aliquot. Collating/merging the rejection criteria results with the corresponding aliquot in the `<obj>@data$data` is a major pain as the former table must be transformed to the (much more reasonable) "1-row-1-aliquot" structure first. I suggest re-structuring the `rejection.criteria`-table as follows (rj = rejection criterion, th = threshold, val = value) ...

rj1.val | ... | rj6.val | rj1.th |  ... | rj6.th | rj1.status | ... | rj6.status
---|---|-----| ------ |---| -------|  ----|----| ----|
x | x | x | x | x | x | x | x | x

... which would make merging the tables much more straightforward and intuitive. 

**Drawback**: 

Since I would suggest to conform to standard naming conventions for column names the table would not be as descriptive as before and we would need to find concise and distinct column names.

**Comment by RLumSK** [comment]
We should stick with the current format. If you have a table, new cases should not add columns but rows. Otherwise it becomes inconsistent. To merge the tables you can use the method `merge` for `data.frame` and use the column `UID` to combine them. In case of doubt, I may suggest to check which `data.frame` structure other packages require (e.g., `ggplot2`). 

Finally, the current structure is not a design error. However, what might become meaningful, would be  a method to reshape the structure on request.

**Comment by tzerk** [comment]
After having had another look [here](https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html) I have to agree with your reply, also partly because I have not thought about utilising the UID for combining the data. Thanks for the reminder, can be closed.
