### ISSUE TITLE
suspicious code in plot_RadialPlot()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#421]
This check seems backwards:
https://github.com/R-Lum/Luminescence/blob/53026b3e17c0f7d7ec36af98a7834b497ee1e214/R/plot_RadialPlot.R#L940-L945
in that when the density calculation succeeds we assign `NA`, but if it fails we try to extract values from it.

**Comment by RLumSK** [comment]
I do agree, it should be the opposite.

**Comment by mcol** [comment]
Fixed in fdf944c4d9d65de20de538977049b3837c532eac.
