### ISSUE TITLE
consolidate code in calc_IEU()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#429]
It seems that the same large block of code is repeated pretty much identically 4 times in the `calc_IEU()` function. This should be consolidated as it's making it quite impossible to fix #424 (R doesn't help that in case of an error in a single function, it doesn't report the line number!).

**Comment by mcol** [comment]
The second of these seems wrong, as on the second line it rounds the wrong variable:
https://github.com/R-Lum/Luminescence/blob/0818581bb3a989e81ff51024aa0b961dde437edc/R/calc_IEU.R#L169-L170
https://github.com/R-Lum/Luminescence/blob/0818581bb3a989e81ff51024aa0b961dde437edc/R/calc_IEU.R#L226-L227
https://github.com/R-Lum/Luminescence/blob/0818581bb3a989e81ff51024aa0b961dde437edc/R/calc_IEU.R#L303-L304
https://github.com/R-Lum/Luminescence/blob/0818581bb3a989e81ff51024aa0b961dde437edc/R/calc_IEU.R#L378-L379

**Comment by mcol** [comment]
Other odd things:

1. The second  for loop effectively reduces to having `i == j` (this happens in all 4 cases)
https://github.com/R-Lum/Luminescence/blob/83a70339b806624b5d5ac2cfa6a0e45951658984/R/calc_IEU.R#L135-L136

2. This is the only time that `Z` is rounded, which seems strange as it's just an intermediate value, so there doesn't seem to be a valid reason to round it
https://github.com/R-Lum/Luminescence/blob/83a70339b806624b5d5ac2cfa6a0e45951658984/R/calc_IEU.R#L319

**Comment by RLumSK** [comment]
If I recall correctly, this was done to avoid some odd minimisation effects I had encountered (+ long calculation times). I think it was just try and error .

P.S.: @mcol: Don't work at the weekend ... :D
