### ISSUE TITLE
calc_AverageDose() - output dstar is matrix and without colnames

### ISSUE THREAD

**Issue by coffeemuggler** [R-Lum/Luminescence#44]
When doing:
AD <- calc_AverageDose(X, 0.1)
X <- get_RLumResults(AD, "dstar")

X is a matrix without col-names. Actually it would be more appropriate to have it as a data frame with names. Would make it easier for further plotting but also the data set is a collection of samples, each described by De and error, i.e., the ideal format for a data frame.

**Comment by RLumSK** [comment]
For the moment we keep the matrix. Thanks.
