### ISSUE TITLE
extract_IrradiationTimes() may fail to update an existing BIN file

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#445]
This way of subsetting will produce the wrong result if `results[,"STEP"] == "irradiation (NA)"` is always `FALSE`:
https://github.com/R-Lum/Luminescence/blob/cc0b78100bba1d55ee091f2eed777ae0a0e0bf89/R/extract_IrradiationTimes.R#L364

In such a case, `which()` would return `integer(0)`, and `subset()` would remove all rows, when actually we'd want to keep them all. Using a logical expression in `subset()` is safer.

When this happens, we may wrongly refuse to update the BIN file.

**Comment by RLumSK** [comment]
@mcol We should not use `subset()` in the package, this causes all kinds of trouble, instead with should check whether there is any irradiation step at all in present. For the moment the function simply relies in the existence of such step (which is not good, I know).
