### ISSUE TITLE
crash in trim_RLum.Data() if an invalid trim_range is given

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#460]
This crashes:
```R
data(ExampleData.RLum.Data.Image, envir = environment())
trim_RLum.Data(ExampleData.RLum.Data.Image, trim_range = c(10, 100)

# Error in object@data[, , max(c(1, range[1])):min(c(ncol(object@data),  :
#   subscript out of bounds
```

**Comment by mcol** [comment]
I found this because one of the existing tests look wrong, as `recordType` should be a character:
https://github.com/R-Lum/Luminescence/blob/4a1946431236b82e950b8b32ce1d7c89f762bc90/tests/testthat/test_trim_RLum.Data.R#L89

**Comment by mcol** [comment]
There's also this typo that will cause a crash on an `RLum.Analysis` object containing `RLum.Data.Spectrum` data:
https://github.com/R-Lum/Luminescence/blob/4a1946431236b82e950b8b32ce1d7c89f762bc90/R/trim_RLum.Data.R#L129

**Comment by RLumSK** [comment]
> I found this because one of the existing tests look wrong, as `recordType` should be a character:
> 
> https://github.com/R-Lum/Luminescence/blob/4a1946431236b82e950b8b32ce1d7c89f762bc90/tests/testthat/test_trim_RLum.Data.R#L89

Actually, recordType has no place there at all. It should be the parameter `trim_range`

**Comment by mcol** [comment]
I'm confused why for `RLum.Data.Image` we operate on the 3rd dimension:
https://github.com/R-Lum/Luminescence/blob/4a1946431236b82e950b8b32ce1d7c89f762bc90/R/trim_RLum.Data.R#L130
https://github.com/R-Lum/Luminescence/blob/4a1946431236b82e950b8b32ce1d7c89f762bc90/R/trim_RLum.Data.R#L117
Isn't `data` in such cases always a standard matrix?

**Comment by mcol** [comment]
No, it's fine, I was mistakenly looking at `RLum.Data.Curve`.
