### ISSUE TITLE
rename Seconds2Gray() to convert_Seconds2Gray()

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#498]
This was noticed during the webinar: when a participant asked how to do that conversion, Thomas' first guess was to search under functions starting with `convert_`, which makes perfect sense. Or are there other reasons to justify the current name?

**Comment by RLumSK** [comment]
It has historical reasons and can be renamed with a "defunct" for the old name.
While we are onto it, we should do the same for the `CW2...` functions, they should also start with `convert_`. However, here we will need a "deprecated" because people my rely on this name.
