### ISSUE TITLE
plot_AbanicoPlot() - summary returns incorrect mean

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#50]
The function `plot_AbanicoPlot` returns an incorrect mean if the parameter `summary` is used. 
Example:

```{r}
df <- data.frame(x = c(216.386185039012, 209.697109762851, 195.609128179155, 200.447792155275, 201.574999360227), y = c(2.21668575178517, 2.03173425290263, 
1.9352060325474, 1.97970741384171, 2.08338086512403))

mean(df$x)
```

This results in a mean of 204.743. However, using calling 

```{r}
plot_AbanicoPlot(data = df, summary = c("mean"))`
```

The mean is 204.61 and NOT 204.743. I guess this comes from the transformation from the log-space and back, since `plot_AbanicoPlot(data = df, summary = c("mean"), log.z = FALSE)` returns the correct value. However, there is no reason why the mean should be different.

**Comment by coffeemuggler** [comment]
I do not see any mistake, here. Indeed, the difference is caused by the 
log-transformed data set.

Micha

**Comment by RLumSK** [comment]
Yes, but there is no reason for this transformation for calculating the mean, at least not so far I can see it. But the results should be understandable. So please calculate the mean using the untransformed values.

**Comment by coffeemuggler** [comment]
Well, have you forgotten about our discussion of this issue with Rex? 
During the article review phase and during the meeting?

Apparently there is a well defined reason for "always" calculate the 
statistics with the log transformed data, and then scaling them back.

Micha

**Comment by RLumSK** [comment]
Ok, it was what again? (I indeed forgot it)

**Comment by coffeemuggler** [comment]
Calculate statistics that were made for symmetric data only with 
symmetrically distributed data.

This is the same way his S script calculated the mean or weighted mean 
for centering the Radial Plot.

exp(mean(log(z)))

Micha

**Comment by RLumSK** [comment]
Ok, but I do not agree for the certain case. The people want to have the `calc_Statistics()` working as written and not with some transformation in between (this is not even stated in the manual!). Since we have this transformation only in the Abanico Plot it looks like a mistake.

**Comment by coffeemuggler** [comment]
Ok, two options:

a) short one: I announce in the AP documentation that with log.z = TRUE 
all statistics are calculated based on the log transformed values.

b) we introduce an arguent log.z to calc_Statistics() and set it 
according to the option in the AP.

Micha

**Comment by RLumSK** [comment]
I prefer the first solution ... the other one is too complicated and no one will understand anything.

**Comment by RLumSK** [comment]
Stop, my mistake, I was too quick. It still makes no sense and neither option (a) nor option (b) can go. What the AP currently returns is the geometric mean, however, this is not the arithmetic mean and should never be termed so. In **R** the user expects the arithmetic mean if `mean()` is used (cf. `?mean`). In other words: Please return the arithmetic mean as requested if the summary keyword is `mean` and not the geometric mean. You can provide it as a plus in the calc_Statistics(). But it should only be returned if the user asks for it, e.g., summary keyword: `mean.geom`. What Rex used in his **S** script is and what the AP returns graphically is a different story.

**Comment by RLumSK** [comment]
News for this bug? Fixed?

**Comment by RLumSK** [comment]
Progress?

**Comment by RLumSK** [comment]
I lost track, was something added in the manual?
