### ISSUE TITLE
group all generics into a single file

### ISSUE THREAD

**Issue by mcol** [R-Lum/Luminescence#526]
This is arguable, but I feel that having all generics in a single file would be a small improvement. By generics I mean the `setGeneric()` declarations. On one hand, we would have fewer files around, but more importantly, it will be clear where new generics should go.

These are the files that currently only contain `setGeneric()`:
- bin_RLum.Data.R
- get_Risoe.BINfileData.R
- length_RLum.R
- metadata.R
- replicate_RLum.R
- set_RLum.R (with some code as well)
- set_Risoe.BINfileData.R
- view.R

These files contain the `setGeneric()` declaration but also the implementation for `list`:
- get_RLum.R (also with implementation for `NULL`)
- melt_RLum.R
- names_RLum.R
- smooth_RLum.R 
- structure_RLum.R 

Whenever a different adds methods for these generics, it must include the respective file. This leads to lines like this one:
```R
#' @include get_RLum.R set_RLum.R names_RLum.R length_RLum.R bin_RLum.Data.R smooth_RLum.R melt_RLum.R
NULL
```

With a single file, that would reduce to `#' @include Luminescence-generics.R`.

Does this sound like a good idea?

**Comment by RLumSK** [comment]
Agreed, go ahead.

**Comment by mcol** [comment]
It turns out that with a single file of name `Luminescence-generics.R`, we don't need the `@include` directives and we can also remove the `Collate` field in the `DESCRIPTION` file: this is fine because already `Luminescence-generics.R` gets sorted before any other file name, so all generics are already defined by the time the function that need to implement them get parsed.
