### ISSUE TITLE
plot_GrowthCurve() ... set NumberIterations.MC to deprecated

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#546]
With fcb34047345b76e43c5cabbc227026ad0d3597a7, I have added a new parameter `n.MC` because this name is used more often and consistently in the package. Currently, `NumberIterations.MC` sets `NumberIterations.MC`, but internally, `n.MC` already took over. With version 1.1.0, `NumberIterations.MC` should be set to deprecated. I expect some trouble down the chain in tests; therefore, the deprecation is at another point in time.

**Comment by RLumSK** [comment]
OK, then make it so. @mcol: Can you please also fix the snapshots?

**Comment by mcol** [comment]
Sure, I'm looking into it.
