### ISSUE TITLE
use_DRAC() ... option to export table with used factors for publication

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#58]
If people are using DRAC in combination with **R** they might cite just DRAC itself and the **R** package 'Luminescence'. However, by doing so, no credit is given to the original authors of all the used conversion factors. To ease the citation the following should be added

- Special output table called 'Used factors' with three columns: `Factor`, `Reference` and `Comment`. The table should be generated as `data.frame` with an option to export as CSV.

- Terminal output with all references used, either as formatted references or as BibTex records, similar to the output created by `citation()`

**Comment by tzerk** [comment]
>  should be generated as data.frame with an option to export as CSV.

Where do we want to have this option and how should it be called? Should this be a standard function argument? I am a bit hesitant, as we usually do not provide separate exporting options and should be done by the user themselves.

**Comment by RLumSK** [comment]
Sorry, my fault. Important is the export as `data.frame` the CSV export can become an example. However, to make sure that the people use it, the data.frame should be returned without further request on the terminal and in the object output.

**Comment by RLumSK** [comment]
Cool, very well!

**Comment by tzerk** [comment]
`use_DRAC()` now by default prints all used references to the console. The output object also includes a list of `bibentry` objects. Not the prettiest implementation, but it gets the job done I guess.
