### ISSUE TITLE
analyse_IRSAR.RF: 'cores' argument not working as expected

### ISSUE THREAD

**Issue by JohannesFriedrich** [R-Lum/Luminescence#60]
The argument `cores` in `method.control` is not working properly. When using a numeric argument, e.g, `cores = 3`, always all cores of the machine are used. Simple example on my machine:

    data(ExampleData.RLum.Analysis, envir = environment())
    analyse_IRSAR.RF(object = IRSAR.RF.Data,
                                     method = "SLIDE",
                                     method.control = list(cores = 2))

> [analyse_IRSAR.RF()] Multicore mode using 4 cores...

Using `cores = "auto"` works as expected: #cores - 2 

> [analyse_IRSAR.RF()] Multicore mode using 2 cores...

**Comment by RLumSK** [comment]
Could not reproduce this behaviour ... for me it works as expect. Can you please check whether this is an Ubuntu releated issue?

**Comment by JohannesFriedrich** [comment]
With the current developer version it seems to work but not with the one on CRAN (0.7.5) ...

**Comment by RLumSK** [comment]
Ok, I consider it as fixed.
