### ISSUE TITLE
analyse_FadingMeasurement() ... normalising

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#62]
Message by G. King: 

` I have just been using the analyse_FadingMeasurement function and have found a small bug. If you are fitting multiple aliquots to determine fading, the function is presently normalising the data to the first measurement of aliquot 1, even where you input the data as a table of multiple sets of three columns for different aliquots.`

**Comment by RLumSK** [comment]
@tzerk Would you mind having a look? I am not sure whether this is a bug, after looking at the code it apears to that just the documentation is imprecise. Internally the multiple table is row binded, however, what is expected here is probably that the table is split into a list of tables.

**Comment by tzerk** [comment]
Will have a look at it. Apparently, the `calc_Kars2008()` function is also affected.

**Comment by tzerk** [comment]
After having had a look at `analyse_FadingMeasurement()` I can see where the current approach might yield deviating results. When providing a table with LxTx values from different aliquots all LxTx values are normalised by the LxTx value of the prompt measurement of the first aliquot. This implicitly assumes that there is no inter-aliquot variation in LxTx values (ie. all yielding indistinguishable photon counts for Lx and Tx).

The alternative approach would be to normalise each aliquot individually by their corresponding LxTx at `tc`. But the more I think about this, the more I lean towards updating the documentation only and not implementing an aliquot specific normalisation. In my opinion trying to normalise each aliquot requires too many "guesstimates" and should really be something the user should take care of before running the function. Thoughts?

**Comment by RLumSK** [comment]
I agree since in particular, the idea is indeed that everything is normalised to the prompt measurement (for one aliquot). This causes no problem until a table (data.frame) is provided with different sets of different prompt measurements for separate aliquots. I prefer an updated documentation.

**Comment by tzerk** [comment]
Updated the documentation. In the `object` argument description the user is now made aware to check the details if data from multiple aliquots are provided. The details now contain a new section on multiple aliquots and the implication for Lx/Tx normalisation. It is suggested to normalise the data manually before running this function.

Feel free to close this issue after checking.

**Comment by RLumSK** [comment]
Thanks, looks good!
