### ISSUE TITLE
calc_HomogeneityTest() ... wrong calculation(?)

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#63]
### Expected behaviour
The test should test against the null hypothesis that the values including the standard errors
are resulting from a common distribution. If P is small enough the null hypothesis should be rejected.

### Observed behaviour
P = 1 is returned even for datasets which are a mix of two distributions. 

### Running mini example

```r
library(Luminescence)
calc_HomogeneityTest(do.call(what = rbind, ExampleData.DeValues))
```

### Reason
Please check code line 101, the `lower.tail = FALSE` appears to be the wrong argument setting.

**Comment by RLumSK** [comment]
Ok, this was probably not the reason, but the log transformation was wrong.

**Comment by RLumSK** [comment]
@tzerk  Please double check. Now it should be ok, however, please check again.

**Comment by tzerk** [comment]
You are absolutely correct. But I have no idea how this error was introduced, as I did also cross-check with the worked example in Galbraith (2003). The proposed fix produces the correct results and thanks for including the test.
