### ISSUE TITLE
calc_MinDose() ... stop flooding the terminal with warnings (rmarkdown code chunk)

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#66]
### Expected behaviour

Result output without none needed and confusing warning messages if run as *rmarkdown* code chunk.

### Observed behaviour

If the function is run within a *rmarkdown* code chunk, the terminal is flooded with warnings. 

```
NaNs producedNA/NaN function evaluationNA/NaN function evaluationNaNs producednumber of items to replace is not a multiple of replacement lengthNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNA/NaN function evaluationNA/NaN function evaluationNA/NaN function evaluationNA/NaN function evaluationNA/NaN function evaluationNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNaNs producedNA/NaN function evaluationNA/NaN function evaluation
```

### Running mini example
 
Run the example below as *rmarkdown* code chunk. 

```r
library(Luminescence)
data(ExampleData.DeValues, envir = environment())
calc_MinDose(ExampleData.DeValues$CA1, sigmab = 0.2)
```
### Reason?

Please check code line 423–424:

```r
 if (!debug)
    options(warn = -1)
```

This option should globally switch of all warnings if `debug` is `FALSE` (the default). However, for whatever reason, it does not work in a *rmarkdown* code chunk. Probably the problem is not coming from the function itself, however, this behaviour is not wanted. Globally disabling warnings is a not a good idea, it prevents the discovery of changed function behaviour if `debug` is not set to `TRUE`.

**Comment by tzerk** [comment]
That's a funny one. As it so happens, I just stumbled across the very same issue. Thanks for pinpointing the issue, will have a look at it.

**Comment by JohannesFriedrich** [comment]
I think it's a `knitr` problem showing the console output, because knitting the file (including your chunk) will not produce any warnings in the final document. When including `debug = TRUE` all expected warnings are implemented in the final document.

**Comment by RLumSK** [comment]
I am afraid to say that this is not correct, the warnings are included (at least) in the HTML-file, using the following yaml-header (otherwise I would not mind). 

```
output: 
  html_notebook
```

Maybe it is not an issue on Ubuntu?

**Comment by JohannesFriedrich** [comment]
Using `html_document` gives no warnings. using `html_notebook` you are right!

**Comment by tzerk** [comment]
Whatever the exact reason may be, I agree that globally disabling warning messages is not a good idea. I removed the `options(warn = -1)` call and will use `suppressWarnings()` to certain function calls. The problem is to identify them all, as `mle*` and all related functions are really... verbose.

**Comment by tzerk** [comment]
The minimal example doesn't produce any warning messages anymore in rmarkdown documents. I reckon you (@RLumSK ) have a more elaborate example that you could use to check if everythings fine now?

**Comment by RLumSK** [comment]
My mistake, please see comments by @JohannesFriedrich above, it seems to appear only for `html_notebook`.

**Comment by RLumSK** [comment]
Looks good to me. Please add news and close the issue.
