### ISSUE TITLE
Retrieve data from 'RLum.Results' objects

### ISSUE THREAD

**Issue by tzerk** [R-Lum/Luminescence#7]
Some functions test if the provided object is of class `RLum.Results` and retrieve the `DE` and `DE.ERROR` data via `get_RLum`. **The problem:** while most `RLum.Results` objects store raw DE values in slot `@data$data`, the `analyse_*`-functions have these values in `@data$De.values`. 

Most or all functions that try to obtain these data check for the `data`, but not the `De.values` slot. Hence, e.g. passing an object from `analyse_SAR.CWOSL` to `plot_KDE` does not work, even though it would make perfect sense.

**Possible solutions:** 
- have all non-analyse functions have additional checks for special originators (`analyse_SAR.CWOSL, analyse_SAR.OSLdata, analyse_IRSAR, analyse_pIRIRsequence`, 
- or add a `@data$data` slot to the `RLum.Results` objects created by the `analyse_*` functions.

For bug report see [message board](https://forum.r-luminescence.de/viewtopic.php?f=3&t=52&sid=f7b1261bf2426fc1887d1cea224a5cf5).

**Comment by RLumSK** [comment]
Done.
