### ISSUE TITLE
analyse_IRSAR.RF(): different decimals with different input formats

### ISSUE THREAD

**Issue by JohannesFriedrich** [R-Lum/Luminescence#70]
### Expected behaviour

No matter what the input format is, the same result and accuracy will be calculated.

### Observed behaviour

BINX-file results show more decimals than XSYG files.

### Running mini example

Take BINX and XSYG file from the same measurement and perform the sliding technique. BINX files always have to decimals, XSYG not.

**Comment by RLumSK** [comment]
Unfortunately, I do not have BINX and XSYG files, but only XSYG-files from such measurements left. Besides, can you please double check whether this is a data format issue? 

The function does not work with XSYG or BIN/BINX-files but with `RLum.Analysis` objects only. The calculation is always the same. However, what differs is that the BIN/BINX-files do not store x-values. Those values are recalculated by `read_BIN2R()` and here we may end up with float numbers, while the XSYG-file, e.g. for an integer channel resolution, will have integer values (even the representation in R is `numeric`, i.e. double in both cases). 

Please just check the imported data and compare the x-values. If they are not precisely similar you have your answer.

**Comment by RLumSK** [comment]
Can I close this issue?

**Comment by JohannesFriedrich** [comment]
jup!
