### ISSUE TITLE
Check `travel_dosimeter` selection in analyse_Al2O3C_Measurement()

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#72]
### Expected behaviour

According to the manual, the aliquot number has to be selected. 

### Observed behaviour

The selection works on the basis of the position number, not the aliquot. 

### Cross-checks

Depending on the selection, the shiny app will be affected as well, i.e. any change has to verify whether the shiny app still does what it should do.

**Comment by mcol** [comment]
We decided to change the manual to reflect the actual implementation.

**Comment by mcol** [comment]
Fixed by 735c204afedc8070aed9089223a43a844751baaa.
