### ISSUE TITLE
RisoeBINfileData-class typo in the file name?

### ISSUE THREAD

**Issue by SebastienHuot** [R-Lum/Luminescence#79]
```r
library(Luminescence)

```
hmm.... perhaps it is me who got it all wrong, but I think the file name was changed for this one

RisoeBINfileData-class.R

In the not so old documentation that I could find, supporting the luminescence package, it talks about Risoe.BINfileData-class

It is also the format (Risoe.BINfileData), with a dot between Risoe and BINfile, that is employed throughout the code. 

the other two classes,
Risoe.BINfileData2RLum.Analysis.R
Risoe.BINfileData2RLum.Data.Curve.R
RisoeBINfileData-class.R

The first two have a dot, in the name

So, maybe it is a tiny typo, that inserted itself over time.

S

**Comment by RLumSK** [comment]
Salut Sébastien, 

Thanks for spotting this. I guess it was never introduced later, but it was never there (the dot in between). The good news is that it has no effect on how the package works, the R-files hold the code only. We arranged them usually with names similar to the function they contain. A design decision to make the code inspection by others a little bit easier. When the package is built, however, only the function names matter and get linked. 

Still, I see your point and thus I modifed the file name.
