### ISSUE TITLE
plot_Histogram() ... return value

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#8]
Please add a return value to the plot function, as in plot_KDE() and plot_AbanicoPlot(). @coffeemuggler @tzerk 

- add argument 'output' (default TRUE, return as invisible())
- add argument 'plot' (default TRUE)

**Comment by RLumSK** [comment]
What about plot_Histogram() ...the request was ... "as in" ...

**Comment by coffeemuggler** [comment]
Da würe es gehen aber mal ehrlich, soll ich das wegen eines machbaren 
Plot anfangen wenn wir wissen, dass es bei den drei anderen nicht geht? ;)

Dann eher warten bis ich doch mal die plot_AbanicoPlot()-Funktion 
grundlegend anfasse und dort alles so baue dass man mit dieser einen 
Funktion auch alle anderen bisherigen Plots bauen kann, oder?

Micha

**Comment by tzerk** [comment]
Why not use `pdf(NULL)` as @RLumSK suggested? In `?pdf` it says:

> 
_file_	  a character string giving the name of the file. If it is of the form "|cmd", the output is piped to the command given by cmd. If it is NULL, then no external file is created (effectively, no drawing occurs), but the device may still be queried (e.g., for size of text).

I reckon that surrounding the function like so should work:

````r
if (!plot)
  pdf(NULL)

<....>

if (!plot)
  dev.off()
```

[Relevant StackOverflow question](http://stackoverflow.com/questions/24759130/disable-plot-display-in-r).

**Comment by RLumSK** [comment]
I may suggest we close this for the moment ...
