### ISSUE TITLE
analyse_SAR.CWOSL: provide more digits to the output

### ISSUE THREAD

**Issue by SebastienHuot** [R-Lum/Luminescence#81]
### Expected behaviour
more, much more, please!
### Observed behaviour
De = 0.01
### Running mini example
de <- analyse_SAR.CWOSL(object = rlum,
                        signal.integral.min = 1,
                        signal.integral.max = 5,
                        background.integral.min = 201,
                        background.integral.max = 250,
                        plot = FALSE,
                        verbose = FALSE)
```r
library(Luminescence)

```
especially relevant when dealing with values near zero

but also in cases where we would have a very precised De. Not very likely, at this moment, but still better to be safe than sorry.

There is no absolute rules to follow, here

Other than, in the case of an intermediary step along a long chain of calculations (such as here; after the De, from individual aliquots, we would want to calculate the average), we must keep as many digits as possible. Otherwise, we become susceptible to rounding errors. Especially if you drop digits, every time you move along the chain of calculations.

such as here. You are dropping digits when calculating the Lx, Ln, Tn and Tx. Well, at least as it is shown in the final RLum.Results object. Internally, you might have preserved all digits. But, from this RLum.Results, I want to calculate the calc_CentralDose, from these (rounded) De.

Thanks!

#

**Comment by RLumSK** [comment]
Thanks and done. I removed the rounding for values returned in the output object. The terminal and graphical output remain untouched.
