### ISSUE TITLE
calc_CentralDose: NaN, NA values must be excluded

### ISSUE THREAD

**Issue by SebastienHuot** [R-Lum/Luminescence#82]
### Expected behaviour
it works, great!
### Observed behaviour
error!
### Running mini example
t <- data.frame(rnorm(10)+5, rnorm(10)+5); t[2,1] = NaN
calc_CentralDose(t)
```r
library(Luminescence)

```
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘"try-error"’ to a data.frame

basically, it stumbles on NaN. Also with a NA value

the code should remove the offending row, then calculate the CAM value

**Comment by RLumSK** [comment]
You will find that all functions will crash if you provide the wrong input. Besides, I see your point.

**Comment by RLumSK** [comment]
I added a new argument `na.rm` which is (R canon) by default set to `FALSE`. However, `NA` values will not break the function anymore but return just `NA`.

**Comment by SebastienHuot** [comment]
Indeed, I am fully aware of this, being a coder myself!

but this is why we all place, right at the top of the code, various < integrity checks >

NaN, NA values would be easy to implement.

tedious to add, to each and every scripted functions. A more holistic approach is to 1st retrieve the data (integrity checks for is there something at all, anything really), then pass this to a sub-function that only perform various integrity checks, then returns a < clean > data back to the main function.

for sure, you can imagine all sort of specific cases, unique to particular scripts: a (logged) radial plot can only take positive values.

it can be easily handled by an argument, that you pass along with the data to be scrutinized by this integrity check subfunction.

Either way, I encourage you to do something about that. It is highly frustrating when you stumbled on an error code. With R, it does not even tell you where and the clue it provides as to the cause is most of the time of no help (at least, to me, at this moment!). Unless you go knee deep into debugger mode. In the specific case of the NaN error, with the calc_CentralDose, I was relaying an RLum results, that I got from analyse_SAR.CWOSL. The NaN came from analyse_SAR.CWOSL. So, it is not really my fault, here, that I am trying to feed inappropriate data into another script.

Why would analyse_SAR.CWOSL provides NaN, for the De, but manages to provides a positive uncertainty, should be left for another time, in another < issue >.

As I am preparing for the R workshop, next Monday, I'm becoming more familiar with the R structure. Still have a lot to learn! I could help you with those things, but not right now! I still have lots to prepare for the workshop.

S

________________________________

**Comment by RLumSK** [comment]
Your comments and contributions are highly welcome. So don't worry. 

When it comes down to R, it works differently. What you want is something that can be done quickly with a GUI, but this is nothing R is made for. Implementing all those tests is not only tedious work, which might be justified; it also costs a lot in terms of overhead. For some functions, it makes sense, `calc_CentralDose()` is one of them, but for others, it does not scale nicely.

>Why would analyse_SAR.CWOSL provides NaN, for the De, but manages to provides a positive uncertainty, should be left for another time, in another < issue >.

This is because the fitting obviously failed, however, for the MC runs (the error estimation), some of the fitting worked. Not nice, but it may happen.
