### ISSUE TITLE
calc_MinDose and calc_MaxDose: parametric wording

### ISSUE THREAD

**Issue by SebastienHuot** [R-Lum/Luminescence#83]
### Running mini example

```r
library(Luminescence)

```
wording issue, in the Luminescence.pdf and also on GitHub

calc_MinDose and calc_MaxDose

Arguments
par numeric (with default): apply the 3- or 4-parametric minimum age model (par=3
or par=4).

parametric -> parameter
< parametric > has a specific connotation in statistic.

**Comment by RLumSK** [comment]
Thanks and done.
