### ISSUE TITLE
calc_MinDose: display gamma, sigma, p0 and mu in their real, absolute units

### ISSUE THREAD

**Issue by SebastienHuot** [R-Lum/Luminescence#84]
### Expected behaviour
gamma = 34.32
### Observed behaviour
gamma = 3.54
### Running mini example

```r
library(Luminescence)

```
in the final table of values, but also with the various graphs

It is very hard to relate to the logarithm transportation

**Comment by RLumSK** [comment]
@tzerk Please have a look and decide. Thanks.

**Comment by tzerk** [comment]
I would be fine with that, though I do not see why this would be necessary. For the console output reporting the non-logged values would be straightforward, changing the likelihood profile plot will be a major problem. These are automatically generated by the `bbmle` package when calculating the profiles. I can only think of some really "hacky" ways to overplot the x-axis labels, which is likely prone to visual bugs and very likely also not worth the effort.

**Comment by RLumSK** [comment]
@tzerk I do agree, would you mind changing the console output accordingly? We do not touch the graphical output.

**Comment by tzerk** [comment]
Will do (when I find the time).

**Comment by RLumSK** [comment]
Sure, this is not at all urgent. Thank you!

**Comment by SebastienHuot** [comment]
thanks, Christoph. Indeed, it is not urgent. I would place this in the bucket of desired changes.

happy to hear that unlogging the console output is easy.

I would also include the < init.values > input argument. If got this right, with log = TRUE, the init.values  for < gamma > and < mu > must be presented as log(gamma) and log(mu). If that is the case, the log transformationS should be handled internally in the code (synchronized with the input argument < log >). It already took me a while to figure out that init.values must be presented as a < list() >, not simply as a < c() >. Yes, I know, the manual explicitly said list(). The fault is mine for that one. So far, I was accustomed to using c(), to construct simple vectors and I do not see the benefit of a list(), over the c(), in the case of the init.values

as for the profile likelihood, I would not dismiss the issue.

first, allow me to take a step back, to explain my reasoning, for you hinted in your original post that you do not find this necessary.

Whenever we take the time to return a result, it must be in the same physical dimension as what was originally submitted. Unless the function is expected to radically transform the input into something else (e.g. from a De and U, Th and K, give me the age). More precisely, in the case of the MAM, the results (gamma and mu) only make sense when they are viewed in the same physical dimension as what was submitted. Otherwise, these simply become a bunch of numbers, without any sense; just like flowers on a wall painting.

These result values are important; therefor, they must be presented in a way that the user will understand. So, not just the final De ([a]symmetric error) statement. but also the final parameters and confidence intervals.

The same principle applies to any graphs generated from the data. A classic mistake, all too frequently seen in presentation and literature are luminescence growth curves with a dose axis in seconds. Or again, a radial plot with ticks marks that do not follow a (easily recognizable) decimal step.

Whenever we take the time to create a graph, it has to be in units/physical dimension that we can easily relate to. Here, for the MAM, for both the gamma and mu profile likelihood, it means showing the x-axis scale in the same physical dimension as what was used in the data submitted to the process. Otherwise, how can anyone relate to it its logged transformation?

I fully agree here, in the specific case of the profile likelihood, that what matters is the shape, not the units on the axis. For my own viewing enjoyment, I have certain graphs that I create without any labels in the axis. Because what matter more in these graphs is the shape. Sometimes, we attach too much importance on numbers. But whenever someone peeks over my shoulder, I must take a step back and explain why I do this. It would be so much easier if everyone would see the World through my eyes! So, whenever these graphs escape the confine of my computer I must take the time to insert the labels on the axis.

I am not suggesting that you should remove the axis labels on the profile likelihood. But if you take the time to show them, they must be in the same physical dimension as the data.

thanks for your in time in looking into this

S

________________________________

**Comment by RLumSK** [comment]
While I do agree in general, we should keep in mind that what the function reflects is a translation of the model by Rex which expects gamma beeing the minimum dose on the log scale. 

@tzerk I double checked how 'bbmle' procudes the plot, the follwing example from the manual, slightly modified, should help: 

```r
library(bbmle)

x <- 0:10
y <- c(26, 17, 13, 12, 20, 5, 9, 8, 5, 4, 8)
d <- data.frame(x,y)
## we have a choice here: (1) don't impose boundaries on the parameters,
##  put up with warning messages about NaN values: 
fit1 <- mle2(y~dpois(lambda=ymax/(1+x/xhalf)),
             start=list(ymax=1,xhalf=1),
             data=d)
p1 <- suppressWarnings(profile(fit1))

##modify S4-object, kick out 2nd object 
p1@profile$xhalf <- NULL

plot(p1,main=c("first","second"),
     xlab=c(~y[max],~x[1/2]),ylab="Signed square root deviance",
     show.points=TRUE, xaxt = "n")
```

Now you have only one plot and you can set a double x-axis (the log and the unlogged) values. 
Its a little hack, but not particular complicated.

**Comment by SebastienHuot** [comment]
I am hard pressed to actually find a published profile likelihood, from the hands of Rex. There is one in QG 2012, but it is on sigma (overdispersion). Not gamma or mu. if I dig deeper, I can find this one

van der Touw, J.W., Galbraith, R.F., Laslett, G.M., 1997. A logistic truncated normal mixture model for overdispersed binomial data. Journal of statistical computation and simulation 59, 349-373. http://doi.org/10.1080/00949659708811866

Figure 4 and 5 shows the age's profile likelihood in age units. It also has a gamma plot, in transformed units. So, I admit that, in the single instance where he published a gamma profile, it was with transformed units.

but also keep in mind that this was for a statistical journal. Not for a geology/archeo audience. Which is the audience you primarily cater to, with the luminescence package. Unless you have other intention.

What I mentioned is a simple concept that we should all follow. Science is already hard as it is, there is no need to complicate it even further when a simpler expression is just as suitable.

and if you truly want to stick with what Rex did, then you should present the negative profile log likelihood, not the transformation you currently employ. I am not asking for that. Properly applied, these representation are all mirror-images of each others. But you previously served me the arguments that you want to replicate what others have done and maintain a sense of familiarity that the user is accustomed to. Your current presentation of the log likelihood deviates from this guiding principle.

I am just offering a suggestion to make this more easily understood, by a greater number of individuals





________________________________

**Comment by RLumSK** [comment]
Don't worry, your suggestions are greatly appreciated, therefore I had given @tzerk the code snippets at hand to allow a straight forward integration.

**Comment by tzerk** [comment]
The `calc_MinDose()` function now always prints the parameter estimates and the confidence interval values in their absolute values, independent of whether the logged or the un-logged model was applied. I made the same changes to the the profile log-likelilhood graphs by directly overwriting the raw data in the `bbmle` objects with their exponential values (if applicable) before plotting them. I found this to be the most straightforward way of doing so, but I only did some fairly limited testing due to time constraints. @SebastienHuot please let me know whether it is now working as you'd expect or there are any bugs.

**Comment by RLumSK** [comment]
@tzerk Thank you very much! I double-checked the new code, however, do you see any possibility to print both, the log and the absolute values? If it takes too much of your time, we stick with the current implementation.

**Comment by tzerk** [comment]
I could certainly do that for the console output. For the plot however this is probably a bit more intricate, as this would require to forgo the automatic 'single plot' feature of the `bbmle::plot()` function and to do it manually with `layout()` or `par()` instead. This way it should be possible to add a second set of axis-labels to each individual plot before moving on to the next plot. I will see what I can do.

**Comment by SebastienHuot** [comment]
thanks Christoph!

displaying the results in their original (input) dimensional scale makes far better sense.

regarding Sebastian's suggestion, I will not re-iterate my arguments that triggered this issue. Only to suggest that presenting < log output > should be left as a optional argument, when calling calc_MinDose(). The default should be to present results in the same input dimensional scale.

Now, in regarding to testing. I have successfully installed the dev_0.9.x version

the various textual outputs appears ok.

likelihood plot for p0 is off-centered! (it is also the case with the 0.9.3 built)

for the sigma output result, it is properly returned, as seen in min@data[["summary"]][["sig"]]. However, in the console output (along with the likelihood profile plot for sigma, the value is exp(sigma)

Also, from inspecting the revised code, it seems you still require init.values in their log() transformation (for gamma and mu). It would be great to update this part.

thanks a lot for your time

Sebastien

**Comment by RLumSK** [comment]
@SebastienHuot Regarding `p0`, I am not a 100 % sure, but for me, it looks like a 'problem' in the plot method of 'bbmle'. If this is the case, I am not sure whether we can tackle this easily.

**Comment by tzerk** [comment]
> The default should be to present results in the same input dimensional scale.

Either I am not understanding correctly, or this contradicts the initial request to have the output always in the absolute units for the output!?  This is getting more and more confusing...

**Comment by tzerk** [comment]
> Also, from inspecting the revised code, it seems you still require init.values in their log() transformation (for gamma and mu). It would be great to update this part.

I've change this in 7e73ed3. `init.values` must now always be in their absolute units. If the logged model is applied (`log = TRUE`) the values must still be given in their absolute units, but are then automatically log transformed before any calculations.

**Comment by tzerk** [comment]
Output after 65ddedc:

```r
data(ExampleData.DeValues, envir = environment())
calc_MinDose(
  data = ExampleData.DeValues$CA1, 
  sigmab = 0.1, 
  par = 4,
  log = TRUE,
  log.output = TRUE # new argument, set to FALSE to hide all output with logged values
)
```

![](https://i.imgur.com/cOwYb3N.png)

**Comment by RLumSK** [comment]
@tzerk Very nice!

**Comment by tzerk** [comment]
>for the sigma output result, it is properly returned, as seen in min@data[["summary"]][["sig"]]. However, in the console output (along with the likelihood profile plot for sigma, the value is exp(sigma)

Isn't it the other way around? The `min@data$summary` data frame has all its output on the absolute scale, independent of whether the logged or non-logged model was applied. It is only for `sigma` that the value was either logged or non-logged, which is of course inconsistent. With 2a0dba1 it is now so that sigma is now also always given in its absolute value.

**Comment by tzerk** [comment]
> @SebastienHuot Regarding p0, I am not a 100 % sure, but for me, it looks like a 'problem' in the plot method of 'bbmle'. If this is the case, I am not sure whether we can tackle this easily.

Yes, this is a problem in the `bbmle` package itself. I haven't had a look at their code for their custom plot method, but its logic for finding some proper `xlim` values sometimes fails. In 8c3fb24 I now override the `xlim` values with a super simple approach, but at least for the one tested data set it gets the job done. Do we want to stick with this approach? If yes, someone please test the code with some more data sets to see whether the plots are reasonable. If not, feel free to revert this commit.

**Before**
![](https://i.imgur.com/RzLteBD.png)

**After**
[Imgur](https://i.imgur.com/7uRKD09.png)
