### ISSUE TITLE
luminescence.pdf -> linkless

### ISSUE THREAD

**Issue by SebastienHuot** [R-Lum/Luminescence#86]
I just noticed that there are no links in the newest luminescence.pdf, tied to page numbers (R topics documented), along with the < see also > section, that suggest other similar functions in the current package. There were there in the previous luminescence.pdf (well, the out-dated version I was carrying around, October 5 2018).

the links are useful for navigation

thanks!

**Comment by RLumSK** [comment]
That is an interesting observation. The CRAN servers create the PDF automatically and cannot tell why the PDF shows now links anymore. Maybe there is something fishy with their LaTeX installation. At least our builds provide still the PDF with links. For the current release, the PDF can be found [here]( https://github.com/R-Lum/Luminescence/blob/master/Luminescence.BuildResults/Luminescence_0.9.3.pdf).

**Comment by SebastienHuot** [comment]
thanks. this one as the links!

what I took, yesterday, was from the CRAN server

________________________________
