### ISSUE TITLE
plot_RLum.Analysis: norm argument for OSL, IRSL

### ISSUE THREAD

**Issue by SebastienHuot** [R-Lum/Luminescence#87]
**new feature**

Showing norm curves is something I frequent do, everyday, for many years. I have struggled for a long time to properly display these norm signals. Especially for OSL,IRSL, where there is often a great difference in amplitude, from one curve to the other. The background (e.g. the tail end of the OSL curve) is often not constant, from curve to curve.

for OSL, IRSL, the approach that I settled with is this
norm OSL, IRSL<i> =(observed<i>. - median(background)) / (max(observed) - median(background))

where background corresponds to the late light background when calculating the Lx/Tx ratio
max(observed) is the what it is!
observed<i>; the individual, observed datapoint

in this way, all norm curves start at 1 and end around 0 (median of zero, with the integrated region, to be more precise).

I take a similar approach with TL

In this way, what you see on the norm plot is the shape of the OSL, IRSL curve. For a given aliquot, this is highly reproducible, if the quartz/feldspar are well-behaved. Those are not well-behaved easily show up, in such norm plot. 

it is worth a look

**Comment by RLumSK** [comment]
Thanks, Sébastien, I guess you have seen that the function already allows automatic normalisation, but you suggest a slightly different approach, right?

**Comment by SebastienHuot** [comment]
yes, different approach

what you currently do is what everyone thinks to do, at first
obversed<i> / max(observed)

this forces every curves to starts at 1 (for OSL, IRSL, whenever they have a moderately strong decaying signal)
but the ends is floating, above 0, to various height, for each curves.

so, the end results in normalizing these curves is rather lost: they decay, quickly. Well, Ok, we do not need to norm to 1, to see that.

but if you normalize the curves at both ends, then what your reveal is the shape of the decay. How uniform and reproducible it is, from each curve of the same aliquot. Even across aliquots and across samples. When they are well-behaved: no ultrafast, for example.

for my data, I overlay these norm curve with a reference curve: calibration quartz or some random feldspar. It serves as an additional, visual guide.

I know we can instead calculate the fast ratio, or attempt OSL component deconvolution. There is simplicity and beauty, in looking at that data. This is one type of display where I strip all axes. I could attach a figure, but I do not know if it ups with on GitHub.





________________________________

**Comment by RLumSK** [comment]
Ok, got you. This sounds like a good improvement. I'll leave this open, and implement it for one of the next versions.

**Comment by RLumSK** [comment]
@SebastienHuot I was further thinking about your suggestion, and I have two questions: 

1. You wrote 'where background corresponds to the late light background', how do you define this? Not in terms of channels, but relative? The last 20 %?

2. You suggested a 'similar approach for TL'. How do you mean this?

Background: The current way could not be more straightforward if `norm = TRUE` I always normalise to the highest point. This works for all curves, whether TL, OSL, or RF. But I guess what you have in mind requires a lot more double-check which kind of curve I have, right?

**Comment by SebastienHuot** [comment]
20 % is a good number. It is what I use for quartz

I this moment, for TL I simply normalize to the max, the traditional way. Because whenever I look at TL, I have a strong signal.

Subtracting a background from the max, for the purpose of normalization, matters more when comparing weak versus strong signal.

Also, for composite signals where the proportion between components is different. For example, in quartz OSL you often have a slow component building up, from cycle to cycle (I do not do elevated temperature OSL, at the of each Lx/Tx).

I have attached examples
raw OSL decay curves [raw.txt](https://github.com/R-Lum/Luminescence/files/3503455/raw.txt)
norm to the max, the traditional way [norm to max.txt](https://github.com/R-Lum/Luminescence/files/3503453/norm.to.max.txt)
norm to the net maximum (after subtracting the background) [norm to net max.txt](https://github.com/R-Lum/Luminescence/files/3503454/norm.to.net.max.txt)

when I look at these curves, I isolate the initial 2 seconds, for display purposes. Along with an overlay from a reference curve (a calibration quartz).

for TL, if I were to implement this, I would calculate the background from the low temperature part of the glow curve. Say, from room to 60 degrees of temperature. If this was done automatically. It is not perfect, for you often have post-irradiation phosphorescence in that part.

**Comment by RLumSK** [comment]
@SebastienHuot Finally, I added the requested feature. If you have time, please have a look at it and check whether it works as expected.

**Comment by RLumSK** [comment]
I will close this issue for the moment because I think that the work is done. However, please feel free to re-open the case if you feel that it is not the case.
