### ISSUE TITLE
plot_RadialPlot: display problem with log.z = FALSE combined with 0 or negative values

### ISSUE THREAD

**Issue by SebastienHuot** [R-Lum/Luminescence#88]
### Expected behaviour
radial scale should go from -1 to 4
data should have values of 0, 1 and 2

### Observed behaviour
radial scale goes from -2 to 3
data have values of -1, 0 and 1

### Running mini example
x <- data.frame("x" = c(0,1,2), "y" = c(0.1,0.1,0.1))
plot_RadialPlot(x, zlim = c(-1,4), log.z = FALSE)

```r
library(Luminescence)

```

Hello!

there is one problem. Possibility two here, highlighted in the sort examples below.

other examples

x <- data.frame("x" = c(0,1,2), "y" = c(0.1,0.1,0.1))
plot_RadialPlot(x, log.z = FALSE)

all good

------------------------
however

x <- data.frame("x" = c(1,2,3), "y" = c(0.1,0.1,0.1))
plot_RadialPlot(x, zlim = c(-1,4), log.z = FALSE)

all good

--------

x <- data.frame("x" = c(-1,2,3), "y" = c(0.1,0.1,0.1))
plot_RadialPlot(x, zlim = c(-1,4), log.z = FALSE)

radial scale goes from -2 to 3
data have values of -2, 1 and 2

--------

x <- data.frame("x" = c(-1,2,3), "y" = c(0.1,0.1,0.1))
plot_RadialPlot(x, log.z = FALSE)

WOW!! words cannot describe what I just saw!

--------

**Comment by RLumSK** [comment]
@SebastienHuot Thanks for double-checking our package. Its indeed a bug. 

@coffeemuggler This comes from the negative value handling, we had discussed this once, but, I guess we never solved it correctly. Do you think you can fix this until the end of August? I got some pressure again from CRAN because of another issue and I will submit a new version of the package soon.

**Comment by RLumSK** [comment]
@coffeemuggler Do you think that this can be fixed for a release early 2020?

**Comment by RLumSK** [comment]
@coffeemuggler I double-checked the old commit you made in 2016 29f88ea855c12cae17a11853ed3d5b40ba31e824. Unfortunately, I cannot make much sense out of it.
If I exclude the relevant lines https://github.com/R-Lum/Luminescence/blob/352d1cca5ff22f321cb8582cc2b1b291e2fdc90f/R/plot_RadialPlot.R#L365-L384 

the plot becomes just fine, it crashes only for `z.log = TRUE` (which makes still sense). So, what should we do? In the meantime, I had two other users complaining and then people start thinking that they cannot trust the plot in general.

**Comment by RLumSK** [comment]
@coffeemuggler Big thanks for the fix! I grabbed it from dev_0.9.0 via cherry-pick and deleted the branch again. 
@SebastienHuot Can you please double-check whether the function now works correctly?

**Comment by SebastienHuot** [comment]
sorry for the delay. I still cannot have R on my office computer. One day, maybe! And, I had problems with installing the latest dev package, with the RStudio cloud.

it looks betters, with the tiny examples.

Good works, to both of you

S

________________________________
