### ISSUE TITLE
 calc_Lamothe2003() - wrong fading corrected Ln/Tn error?

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/Luminescence#96]
Transferred issue from an e-mail discussion with the *Lux* group in Montréal, for the example below the Ln/Tn error after fading correction appears to be too small. 

```r
library(Luminescence)
df <- data.frame(
  Dose = c(0,600,150,300,1200,3200,0,600),
  LxTx = c(2.124,2.29,0.613,1.166,3.879,7.857,0.021,2.184),
  LxTx_X = c(0.046,0.049,0.013,0.025,0.083,0.169,0.001,0.047)
)

results <- calc_Lamothe2003(
  object = df,
  dose_rate.envir = c(1.75,0.02),
  dose_rate.source = c(0.125,0.002),
  g_value = c(4.0,0.2),
  tc = 400,
  tc.g_value = 172800,
  plot = FALSE
)

cat(">> Original LnTn error:", round(df$LxTx_X[1]/df$LxTx[1] * 100,1), "%","\n")
cat(">> Corrected LnTn error:", round(results$data$LnTn_AFTER.ERROR/results$data$LnTn_AFTER * 100,1), "%")
```

The error calculation might be uncorrected, in particular the following part needs to be checked: https://github.com/R-Lum/Luminescence/blob/004fa74610235064602ba777c8b85e766364746e/R/calc_Lamothe2003.R#L244-L260

Why we have the term `(1/Fading_C - 1)`?

**Comment by RLumSK** [comment]
@mcol Can you double check the math here?

**Comment by mcol** [comment]
We further discussed this yesterday and looked back at old email conversations regarding this, and as I also could not find a justification for the extra term, we decided to go ahead and remove it.
